package com.core.entity;

public class BaseType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_type.id
     *
     * @mbg.generated Mon Dec 18 10:30:11 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_type.name
     *
     * @mbg.generated Mon Dec 18 10:30:11 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_type.type
     *
     * @mbg.generated Mon Dec 18 10:30:11 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_type.remark
     *
     * @mbg.generated Mon Dec 18 10:30:11 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_type.order_num
     *
     * @mbg.generated Mon Dec 18 10:30:11 CST 2017
     */
    private Integer orderNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_type.id
     *
     * @return the value of base_type.id
     *
     * @mbg.generated Mon Dec 18 10:30:11 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_type.id
     *
     * @param id the value for base_type.id
     *
     * @mbg.generated Mon Dec 18 10:30:11 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_type.name
     *
     * @return the value of base_type.name
     *
     * @mbg.generated Mon Dec 18 10:30:11 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_type.name
     *
     * @param name the value for base_type.name
     *
     * @mbg.generated Mon Dec 18 10:30:11 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_type.type
     *
     * @return the value of base_type.type
     *
     * @mbg.generated Mon Dec 18 10:30:11 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_type.type
     *
     * @param type the value for base_type.type
     *
     * @mbg.generated Mon Dec 18 10:30:11 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_type.remark
     *
     * @return the value of base_type.remark
     *
     * @mbg.generated Mon Dec 18 10:30:11 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_type.remark
     *
     * @param remark the value for base_type.remark
     *
     * @mbg.generated Mon Dec 18 10:30:11 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_type.order_num
     *
     * @return the value of base_type.order_num
     *
     * @mbg.generated Mon Dec 18 10:30:11 CST 2017
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_type.order_num
     *
     * @param orderNum the value for base_type.order_num
     *
     * @mbg.generated Mon Dec 18 10:30:11 CST 2017
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }
}