package com.core.entity;

public class Foreman {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.id
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.code
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.name
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.type
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.password
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.idcard
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.mobile
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.create_date
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foreman.remark
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.id
     *
     * @return the value of foreman.id
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.id
     *
     * @param id the value for foreman.id
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.code
     *
     * @return the value of foreman.code
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.code
     *
     * @param code the value for foreman.code
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.name
     *
     * @return the value of foreman.name
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.name
     *
     * @param name the value for foreman.name
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.type
     *
     * @return the value of foreman.type
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.type
     *
     * @param type the value for foreman.type
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.password
     *
     * @return the value of foreman.password
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.password
     *
     * @param password the value for foreman.password
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.idcard
     *
     * @return the value of foreman.idcard
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.idcard
     *
     * @param idcard the value for foreman.idcard
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.mobile
     *
     * @return the value of foreman.mobile
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.mobile
     *
     * @param mobile the value for foreman.mobile
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.create_date
     *
     * @return the value of foreman.create_date
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.create_date
     *
     * @param createDate the value for foreman.create_date
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foreman.remark
     *
     * @return the value of foreman.remark
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foreman.remark
     *
     * @param remark the value for foreman.remark
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}