package com.core.entity;

import java.util.ArrayList;
import java.util.List;

public class LaborCostExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table labor_cost
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table labor_cost
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table labor_cost
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor_cost
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public LaborCostExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor_cost
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor_cost
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor_cost
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor_cost
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor_cost
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor_cost
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor_cost
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor_cost
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor_cost
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labor_cost
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table labor_cost
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectIsNull() {
            addCriterion("project is null");
            return (Criteria) this;
        }

        public Criteria andProjectIsNotNull() {
            addCriterion("project is not null");
            return (Criteria) this;
        }

        public Criteria andProjectEqualTo(Integer value) {
            addCriterion("project =", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectNotEqualTo(Integer value) {
            addCriterion("project <>", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectGreaterThan(Integer value) {
            addCriterion("project >", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectGreaterThanOrEqualTo(Integer value) {
            addCriterion("project >=", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectLessThan(Integer value) {
            addCriterion("project <", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectLessThanOrEqualTo(Integer value) {
            addCriterion("project <=", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectIn(List<Integer> values) {
            addCriterion("project in", values, "project");
            return (Criteria) this;
        }

        public Criteria andProjectNotIn(List<Integer> values) {
            addCriterion("project not in", values, "project");
            return (Criteria) this;
        }

        public Criteria andProjectBetween(Integer value1, Integer value2) {
            addCriterion("project between", value1, value2, "project");
            return (Criteria) this;
        }

        public Criteria andProjectNotBetween(Integer value1, Integer value2) {
            addCriterion("project not between", value1, value2, "project");
            return (Criteria) this;
        }

        public Criteria andProgramIsNull() {
            addCriterion("program is null");
            return (Criteria) this;
        }

        public Criteria andProgramIsNotNull() {
            addCriterion("program is not null");
            return (Criteria) this;
        }

        public Criteria andProgramEqualTo(String value) {
            addCriterion("program =", value, "program");
            return (Criteria) this;
        }

        public Criteria andProgramNotEqualTo(String value) {
            addCriterion("program <>", value, "program");
            return (Criteria) this;
        }

        public Criteria andProgramGreaterThan(String value) {
            addCriterion("program >", value, "program");
            return (Criteria) this;
        }

        public Criteria andProgramGreaterThanOrEqualTo(String value) {
            addCriterion("program >=", value, "program");
            return (Criteria) this;
        }

        public Criteria andProgramLessThan(String value) {
            addCriterion("program <", value, "program");
            return (Criteria) this;
        }

        public Criteria andProgramLessThanOrEqualTo(String value) {
            addCriterion("program <=", value, "program");
            return (Criteria) this;
        }

        public Criteria andProgramLike(String value) {
            addCriterion("program like", value, "program");
            return (Criteria) this;
        }

        public Criteria andProgramNotLike(String value) {
            addCriterion("program not like", value, "program");
            return (Criteria) this;
        }

        public Criteria andProgramIn(List<String> values) {
            addCriterion("program in", values, "program");
            return (Criteria) this;
        }

        public Criteria andProgramNotIn(List<String> values) {
            addCriterion("program not in", values, "program");
            return (Criteria) this;
        }

        public Criteria andProgramBetween(String value1, String value2) {
            addCriterion("program between", value1, value2, "program");
            return (Criteria) this;
        }

        public Criteria andProgramNotBetween(String value1, String value2) {
            addCriterion("program not between", value1, value2, "program");
            return (Criteria) this;
        }

        public Criteria andNodeIsNull() {
            addCriterion("node is null");
            return (Criteria) this;
        }

        public Criteria andNodeIsNotNull() {
            addCriterion("node is not null");
            return (Criteria) this;
        }

        public Criteria andNodeEqualTo(String value) {
            addCriterion("node =", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeNotEqualTo(String value) {
            addCriterion("node <>", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeGreaterThan(String value) {
            addCriterion("node >", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeGreaterThanOrEqualTo(String value) {
            addCriterion("node >=", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeLessThan(String value) {
            addCriterion("node <", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeLessThanOrEqualTo(String value) {
            addCriterion("node <=", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeLike(String value) {
            addCriterion("node like", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeNotLike(String value) {
            addCriterion("node not like", value, "node");
            return (Criteria) this;
        }

        public Criteria andNodeIn(List<String> values) {
            addCriterion("node in", values, "node");
            return (Criteria) this;
        }

        public Criteria andNodeNotIn(List<String> values) {
            addCriterion("node not in", values, "node");
            return (Criteria) this;
        }

        public Criteria andNodeBetween(String value1, String value2) {
            addCriterion("node between", value1, value2, "node");
            return (Criteria) this;
        }

        public Criteria andNodeNotBetween(String value1, String value2) {
            addCriterion("node not between", value1, value2, "node");
            return (Criteria) this;
        }

        public Criteria andIprocedureIsNull() {
            addCriterion("iprocedure is null");
            return (Criteria) this;
        }

        public Criteria andIprocedureIsNotNull() {
            addCriterion("iprocedure is not null");
            return (Criteria) this;
        }

        public Criteria andIprocedureEqualTo(String value) {
            addCriterion("iprocedure =", value, "iprocedure");
            return (Criteria) this;
        }

        public Criteria andIprocedureNotEqualTo(String value) {
            addCriterion("iprocedure <>", value, "iprocedure");
            return (Criteria) this;
        }

        public Criteria andIprocedureGreaterThan(String value) {
            addCriterion("iprocedure >", value, "iprocedure");
            return (Criteria) this;
        }

        public Criteria andIprocedureGreaterThanOrEqualTo(String value) {
            addCriterion("iprocedure >=", value, "iprocedure");
            return (Criteria) this;
        }

        public Criteria andIprocedureLessThan(String value) {
            addCriterion("iprocedure <", value, "iprocedure");
            return (Criteria) this;
        }

        public Criteria andIprocedureLessThanOrEqualTo(String value) {
            addCriterion("iprocedure <=", value, "iprocedure");
            return (Criteria) this;
        }

        public Criteria andIprocedureLike(String value) {
            addCriterion("iprocedure like", value, "iprocedure");
            return (Criteria) this;
        }

        public Criteria andIprocedureNotLike(String value) {
            addCriterion("iprocedure not like", value, "iprocedure");
            return (Criteria) this;
        }

        public Criteria andIprocedureIn(List<String> values) {
            addCriterion("iprocedure in", values, "iprocedure");
            return (Criteria) this;
        }

        public Criteria andIprocedureNotIn(List<String> values) {
            addCriterion("iprocedure not in", values, "iprocedure");
            return (Criteria) this;
        }

        public Criteria andIprocedureBetween(String value1, String value2) {
            addCriterion("iprocedure between", value1, value2, "iprocedure");
            return (Criteria) this;
        }

        public Criteria andIprocedureNotBetween(String value1, String value2) {
            addCriterion("iprocedure not between", value1, value2, "iprocedure");
            return (Criteria) this;
        }

        public Criteria andForemanIsNull() {
            addCriterion("foreman is null");
            return (Criteria) this;
        }

        public Criteria andForemanIsNotNull() {
            addCriterion("foreman is not null");
            return (Criteria) this;
        }

        public Criteria andForemanEqualTo(Integer value) {
            addCriterion("foreman =", value, "foreman");
            return (Criteria) this;
        }

        public Criteria andForemanNotEqualTo(Integer value) {
            addCriterion("foreman <>", value, "foreman");
            return (Criteria) this;
        }

        public Criteria andForemanGreaterThan(Integer value) {
            addCriterion("foreman >", value, "foreman");
            return (Criteria) this;
        }

        public Criteria andForemanGreaterThanOrEqualTo(Integer value) {
            addCriterion("foreman >=", value, "foreman");
            return (Criteria) this;
        }

        public Criteria andForemanLessThan(Integer value) {
            addCriterion("foreman <", value, "foreman");
            return (Criteria) this;
        }

        public Criteria andForemanLessThanOrEqualTo(Integer value) {
            addCriterion("foreman <=", value, "foreman");
            return (Criteria) this;
        }

        public Criteria andForemanIn(List<Integer> values) {
            addCriterion("foreman in", values, "foreman");
            return (Criteria) this;
        }

        public Criteria andForemanNotIn(List<Integer> values) {
            addCriterion("foreman not in", values, "foreman");
            return (Criteria) this;
        }

        public Criteria andForemanBetween(Integer value1, Integer value2) {
            addCriterion("foreman between", value1, value2, "foreman");
            return (Criteria) this;
        }

        public Criteria andForemanNotBetween(Integer value1, Integer value2) {
            addCriterion("foreman not between", value1, value2, "foreman");
            return (Criteria) this;
        }

        public Criteria andForemanNameIsNull() {
            addCriterion("foreman_name is null");
            return (Criteria) this;
        }

        public Criteria andForemanNameIsNotNull() {
            addCriterion("foreman_name is not null");
            return (Criteria) this;
        }

        public Criteria andForemanNameEqualTo(String value) {
            addCriterion("foreman_name =", value, "foremanName");
            return (Criteria) this;
        }

        public Criteria andForemanNameNotEqualTo(String value) {
            addCriterion("foreman_name <>", value, "foremanName");
            return (Criteria) this;
        }

        public Criteria andForemanNameGreaterThan(String value) {
            addCriterion("foreman_name >", value, "foremanName");
            return (Criteria) this;
        }

        public Criteria andForemanNameGreaterThanOrEqualTo(String value) {
            addCriterion("foreman_name >=", value, "foremanName");
            return (Criteria) this;
        }

        public Criteria andForemanNameLessThan(String value) {
            addCriterion("foreman_name <", value, "foremanName");
            return (Criteria) this;
        }

        public Criteria andForemanNameLessThanOrEqualTo(String value) {
            addCriterion("foreman_name <=", value, "foremanName");
            return (Criteria) this;
        }

        public Criteria andForemanNameLike(String value) {
            addCriterion("foreman_name like", value, "foremanName");
            return (Criteria) this;
        }

        public Criteria andForemanNameNotLike(String value) {
            addCriterion("foreman_name not like", value, "foremanName");
            return (Criteria) this;
        }

        public Criteria andForemanNameIn(List<String> values) {
            addCriterion("foreman_name in", values, "foremanName");
            return (Criteria) this;
        }

        public Criteria andForemanNameNotIn(List<String> values) {
            addCriterion("foreman_name not in", values, "foremanName");
            return (Criteria) this;
        }

        public Criteria andForemanNameBetween(String value1, String value2) {
            addCriterion("foreman_name between", value1, value2, "foremanName");
            return (Criteria) this;
        }

        public Criteria andForemanNameNotBetween(String value1, String value2) {
            addCriterion("foreman_name not between", value1, value2, "foremanName");
            return (Criteria) this;
        }

        public Criteria andWorkerTypeIsNull() {
            addCriterion("worker_type is null");
            return (Criteria) this;
        }

        public Criteria andWorkerTypeIsNotNull() {
            addCriterion("worker_type is not null");
            return (Criteria) this;
        }

        public Criteria andWorkerTypeEqualTo(String value) {
            addCriterion("worker_type =", value, "workerType");
            return (Criteria) this;
        }

        public Criteria andWorkerTypeNotEqualTo(String value) {
            addCriterion("worker_type <>", value, "workerType");
            return (Criteria) this;
        }

        public Criteria andWorkerTypeGreaterThan(String value) {
            addCriterion("worker_type >", value, "workerType");
            return (Criteria) this;
        }

        public Criteria andWorkerTypeGreaterThanOrEqualTo(String value) {
            addCriterion("worker_type >=", value, "workerType");
            return (Criteria) this;
        }

        public Criteria andWorkerTypeLessThan(String value) {
            addCriterion("worker_type <", value, "workerType");
            return (Criteria) this;
        }

        public Criteria andWorkerTypeLessThanOrEqualTo(String value) {
            addCriterion("worker_type <=", value, "workerType");
            return (Criteria) this;
        }

        public Criteria andWorkerTypeLike(String value) {
            addCriterion("worker_type like", value, "workerType");
            return (Criteria) this;
        }

        public Criteria andWorkerTypeNotLike(String value) {
            addCriterion("worker_type not like", value, "workerType");
            return (Criteria) this;
        }

        public Criteria andWorkerTypeIn(List<String> values) {
            addCriterion("worker_type in", values, "workerType");
            return (Criteria) this;
        }

        public Criteria andWorkerTypeNotIn(List<String> values) {
            addCriterion("worker_type not in", values, "workerType");
            return (Criteria) this;
        }

        public Criteria andWorkerTypeBetween(String value1, String value2) {
            addCriterion("worker_type between", value1, value2, "workerType");
            return (Criteria) this;
        }

        public Criteria andWorkerTypeNotBetween(String value1, String value2) {
            addCriterion("worker_type not between", value1, value2, "workerType");
            return (Criteria) this;
        }

        public Criteria andWorkerIsNull() {
            addCriterion("worker is null");
            return (Criteria) this;
        }

        public Criteria andWorkerIsNotNull() {
            addCriterion("worker is not null");
            return (Criteria) this;
        }

        public Criteria andWorkerEqualTo(Integer value) {
            addCriterion("worker =", value, "worker");
            return (Criteria) this;
        }

        public Criteria andWorkerNotEqualTo(Integer value) {
            addCriterion("worker <>", value, "worker");
            return (Criteria) this;
        }

        public Criteria andWorkerGreaterThan(Integer value) {
            addCriterion("worker >", value, "worker");
            return (Criteria) this;
        }

        public Criteria andWorkerGreaterThanOrEqualTo(Integer value) {
            addCriterion("worker >=", value, "worker");
            return (Criteria) this;
        }

        public Criteria andWorkerLessThan(Integer value) {
            addCriterion("worker <", value, "worker");
            return (Criteria) this;
        }

        public Criteria andWorkerLessThanOrEqualTo(Integer value) {
            addCriterion("worker <=", value, "worker");
            return (Criteria) this;
        }

        public Criteria andWorkerIn(List<Integer> values) {
            addCriterion("worker in", values, "worker");
            return (Criteria) this;
        }

        public Criteria andWorkerNotIn(List<Integer> values) {
            addCriterion("worker not in", values, "worker");
            return (Criteria) this;
        }

        public Criteria andWorkerBetween(Integer value1, Integer value2) {
            addCriterion("worker between", value1, value2, "worker");
            return (Criteria) this;
        }

        public Criteria andWorkerNotBetween(Integer value1, Integer value2) {
            addCriterion("worker not between", value1, value2, "worker");
            return (Criteria) this;
        }

        public Criteria andIcountIsNull() {
            addCriterion("icount is null");
            return (Criteria) this;
        }

        public Criteria andIcountIsNotNull() {
            addCriterion("icount is not null");
            return (Criteria) this;
        }

        public Criteria andIcountEqualTo(Integer value) {
            addCriterion("icount =", value, "icount");
            return (Criteria) this;
        }

        public Criteria andIcountNotEqualTo(Integer value) {
            addCriterion("icount <>", value, "icount");
            return (Criteria) this;
        }

        public Criteria andIcountGreaterThan(Integer value) {
            addCriterion("icount >", value, "icount");
            return (Criteria) this;
        }

        public Criteria andIcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("icount >=", value, "icount");
            return (Criteria) this;
        }

        public Criteria andIcountLessThan(Integer value) {
            addCriterion("icount <", value, "icount");
            return (Criteria) this;
        }

        public Criteria andIcountLessThanOrEqualTo(Integer value) {
            addCriterion("icount <=", value, "icount");
            return (Criteria) this;
        }

        public Criteria andIcountIn(List<Integer> values) {
            addCriterion("icount in", values, "icount");
            return (Criteria) this;
        }

        public Criteria andIcountNotIn(List<Integer> values) {
            addCriterion("icount not in", values, "icount");
            return (Criteria) this;
        }

        public Criteria andIcountBetween(Integer value1, Integer value2) {
            addCriterion("icount between", value1, value2, "icount");
            return (Criteria) this;
        }

        public Criteria andIcountNotBetween(Integer value1, Integer value2) {
            addCriterion("icount not between", value1, value2, "icount");
            return (Criteria) this;
        }

        public Criteria andBaseTypeIsNull() {
            addCriterion("base_type is null");
            return (Criteria) this;
        }

        public Criteria andBaseTypeIsNotNull() {
            addCriterion("base_type is not null");
            return (Criteria) this;
        }

        public Criteria andBaseTypeEqualTo(String value) {
            addCriterion("base_type =", value, "baseType");
            return (Criteria) this;
        }

        public Criteria andBaseTypeNotEqualTo(String value) {
            addCriterion("base_type <>", value, "baseType");
            return (Criteria) this;
        }

        public Criteria andBaseTypeGreaterThan(String value) {
            addCriterion("base_type >", value, "baseType");
            return (Criteria) this;
        }

        public Criteria andBaseTypeGreaterThanOrEqualTo(String value) {
            addCriterion("base_type >=", value, "baseType");
            return (Criteria) this;
        }

        public Criteria andBaseTypeLessThan(String value) {
            addCriterion("base_type <", value, "baseType");
            return (Criteria) this;
        }

        public Criteria andBaseTypeLessThanOrEqualTo(String value) {
            addCriterion("base_type <=", value, "baseType");
            return (Criteria) this;
        }

        public Criteria andBaseTypeLike(String value) {
            addCriterion("base_type like", value, "baseType");
            return (Criteria) this;
        }

        public Criteria andBaseTypeNotLike(String value) {
            addCriterion("base_type not like", value, "baseType");
            return (Criteria) this;
        }

        public Criteria andBaseTypeIn(List<String> values) {
            addCriterion("base_type in", values, "baseType");
            return (Criteria) this;
        }

        public Criteria andBaseTypeNotIn(List<String> values) {
            addCriterion("base_type not in", values, "baseType");
            return (Criteria) this;
        }

        public Criteria andBaseTypeBetween(String value1, String value2) {
            addCriterion("base_type between", value1, value2, "baseType");
            return (Criteria) this;
        }

        public Criteria andBaseTypeNotBetween(String value1, String value2) {
            addCriterion("base_type not between", value1, value2, "baseType");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Integer value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Integer value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Integer value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Integer value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Integer value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Integer> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Integer> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Integer value1, Integer value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIsNull() {
            addCriterion("unit_price is null");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIsNotNull() {
            addCriterion("unit_price is not null");
            return (Criteria) this;
        }

        public Criteria andUnitPriceEqualTo(Integer value) {
            addCriterion("unit_price =", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotEqualTo(Integer value) {
            addCriterion("unit_price <>", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceGreaterThan(Integer value) {
            addCriterion("unit_price >", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("unit_price >=", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceLessThan(Integer value) {
            addCriterion("unit_price <", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceLessThanOrEqualTo(Integer value) {
            addCriterion("unit_price <=", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIn(List<Integer> values) {
            addCriterion("unit_price in", values, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotIn(List<Integer> values) {
            addCriterion("unit_price not in", values, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceBetween(Integer value1, Integer value2) {
            addCriterion("unit_price between", value1, value2, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("unit_price not between", value1, value2, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceTypeIsNull() {
            addCriterion("unit_price_type is null");
            return (Criteria) this;
        }

        public Criteria andUnitPriceTypeIsNotNull() {
            addCriterion("unit_price_type is not null");
            return (Criteria) this;
        }

        public Criteria andUnitPriceTypeEqualTo(String value) {
            addCriterion("unit_price_type =", value, "unitPriceType");
            return (Criteria) this;
        }

        public Criteria andUnitPriceTypeNotEqualTo(String value) {
            addCriterion("unit_price_type <>", value, "unitPriceType");
            return (Criteria) this;
        }

        public Criteria andUnitPriceTypeGreaterThan(String value) {
            addCriterion("unit_price_type >", value, "unitPriceType");
            return (Criteria) this;
        }

        public Criteria andUnitPriceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("unit_price_type >=", value, "unitPriceType");
            return (Criteria) this;
        }

        public Criteria andUnitPriceTypeLessThan(String value) {
            addCriterion("unit_price_type <", value, "unitPriceType");
            return (Criteria) this;
        }

        public Criteria andUnitPriceTypeLessThanOrEqualTo(String value) {
            addCriterion("unit_price_type <=", value, "unitPriceType");
            return (Criteria) this;
        }

        public Criteria andUnitPriceTypeLike(String value) {
            addCriterion("unit_price_type like", value, "unitPriceType");
            return (Criteria) this;
        }

        public Criteria andUnitPriceTypeNotLike(String value) {
            addCriterion("unit_price_type not like", value, "unitPriceType");
            return (Criteria) this;
        }

        public Criteria andUnitPriceTypeIn(List<String> values) {
            addCriterion("unit_price_type in", values, "unitPriceType");
            return (Criteria) this;
        }

        public Criteria andUnitPriceTypeNotIn(List<String> values) {
            addCriterion("unit_price_type not in", values, "unitPriceType");
            return (Criteria) this;
        }

        public Criteria andUnitPriceTypeBetween(String value1, String value2) {
            addCriterion("unit_price_type between", value1, value2, "unitPriceType");
            return (Criteria) this;
        }

        public Criteria andUnitPriceTypeNotBetween(String value1, String value2) {
            addCriterion("unit_price_type not between", value1, value2, "unitPriceType");
            return (Criteria) this;
        }

        public Criteria andWorkerNumsIsNull() {
            addCriterion("worker_nums is null");
            return (Criteria) this;
        }

        public Criteria andWorkerNumsIsNotNull() {
            addCriterion("worker_nums is not null");
            return (Criteria) this;
        }

        public Criteria andWorkerNumsEqualTo(Integer value) {
            addCriterion("worker_nums =", value, "workerNums");
            return (Criteria) this;
        }

        public Criteria andWorkerNumsNotEqualTo(Integer value) {
            addCriterion("worker_nums <>", value, "workerNums");
            return (Criteria) this;
        }

        public Criteria andWorkerNumsGreaterThan(Integer value) {
            addCriterion("worker_nums >", value, "workerNums");
            return (Criteria) this;
        }

        public Criteria andWorkerNumsGreaterThanOrEqualTo(Integer value) {
            addCriterion("worker_nums >=", value, "workerNums");
            return (Criteria) this;
        }

        public Criteria andWorkerNumsLessThan(Integer value) {
            addCriterion("worker_nums <", value, "workerNums");
            return (Criteria) this;
        }

        public Criteria andWorkerNumsLessThanOrEqualTo(Integer value) {
            addCriterion("worker_nums <=", value, "workerNums");
            return (Criteria) this;
        }

        public Criteria andWorkerNumsIn(List<Integer> values) {
            addCriterion("worker_nums in", values, "workerNums");
            return (Criteria) this;
        }

        public Criteria andWorkerNumsNotIn(List<Integer> values) {
            addCriterion("worker_nums not in", values, "workerNums");
            return (Criteria) this;
        }

        public Criteria andWorkerNumsBetween(Integer value1, Integer value2) {
            addCriterion("worker_nums between", value1, value2, "workerNums");
            return (Criteria) this;
        }

        public Criteria andWorkerNumsNotBetween(Integer value1, Integer value2) {
            addCriterion("worker_nums not between", value1, value2, "workerNums");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("create_date like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("create_date not like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<String> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<String> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(String value) {
            addCriterion("date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(String value) {
            addCriterion("date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(String value) {
            addCriterion("date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(String value) {
            addCriterion("date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(String value) {
            addCriterion("date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(String value) {
            addCriterion("date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLike(String value) {
            addCriterion("date like", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotLike(String value) {
            addCriterion("date not like", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<String> values) {
            addCriterion("date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<String> values) {
            addCriterion("date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(String value1, String value2) {
            addCriterion("date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(String value1, String value2) {
            addCriterion("date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andStaffNameIsNull() {
            addCriterion("staff_name is null");
            return (Criteria) this;
        }

        public Criteria andStaffNameIsNotNull() {
            addCriterion("staff_name is not null");
            return (Criteria) this;
        }

        public Criteria andStaffNameEqualTo(String value) {
            addCriterion("staff_name =", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotEqualTo(String value) {
            addCriterion("staff_name <>", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameGreaterThan(String value) {
            addCriterion("staff_name >", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameGreaterThanOrEqualTo(String value) {
            addCriterion("staff_name >=", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLessThan(String value) {
            addCriterion("staff_name <", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLessThanOrEqualTo(String value) {
            addCriterion("staff_name <=", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLike(String value) {
            addCriterion("staff_name like", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotLike(String value) {
            addCriterion("staff_name not like", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameIn(List<String> values) {
            addCriterion("staff_name in", values, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotIn(List<String> values) {
            addCriterion("staff_name not in", values, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameBetween(String value1, String value2) {
            addCriterion("staff_name between", value1, value2, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotBetween(String value1, String value2) {
            addCriterion("staff_name not between", value1, value2, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffIsNull() {
            addCriterion("staff is null");
            return (Criteria) this;
        }

        public Criteria andStaffIsNotNull() {
            addCriterion("staff is not null");
            return (Criteria) this;
        }

        public Criteria andStaffEqualTo(Integer value) {
            addCriterion("staff =", value, "staff");
            return (Criteria) this;
        }

        public Criteria andStaffNotEqualTo(Integer value) {
            addCriterion("staff <>", value, "staff");
            return (Criteria) this;
        }

        public Criteria andStaffGreaterThan(Integer value) {
            addCriterion("staff >", value, "staff");
            return (Criteria) this;
        }

        public Criteria andStaffGreaterThanOrEqualTo(Integer value) {
            addCriterion("staff >=", value, "staff");
            return (Criteria) this;
        }

        public Criteria andStaffLessThan(Integer value) {
            addCriterion("staff <", value, "staff");
            return (Criteria) this;
        }

        public Criteria andStaffLessThanOrEqualTo(Integer value) {
            addCriterion("staff <=", value, "staff");
            return (Criteria) this;
        }

        public Criteria andStaffIn(List<Integer> values) {
            addCriterion("staff in", values, "staff");
            return (Criteria) this;
        }

        public Criteria andStaffNotIn(List<Integer> values) {
            addCriterion("staff not in", values, "staff");
            return (Criteria) this;
        }

        public Criteria andStaffBetween(Integer value1, Integer value2) {
            addCriterion("staff between", value1, value2, "staff");
            return (Criteria) this;
        }

        public Criteria andStaffNotBetween(Integer value1, Integer value2) {
            addCriterion("staff not between", value1, value2, "staff");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table labor_cost
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 25 10:11:12 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table labor_cost
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}