package com.core.entity;

public class MechanicsPrice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.id
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.project
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private Integer project;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.program
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private String program;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.node
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private String node;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.iprocedure
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private String iprocedure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.mechanic
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private Integer mechanic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.mechanic_name
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private String mechanicName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.driver_name
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private String driverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.plate_number
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private String plateNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.base_type
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private String baseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.icount
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private Integer icount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.unit_price
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private Integer unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.unit_price_type
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private String unitPriceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.date
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.create_date
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.staff_name
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private String staffName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.staff
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private Integer staff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.price
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanics_price.remark
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.id
     *
     * @return the value of mechanics_price.id
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.id
     *
     * @param id the value for mechanics_price.id
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.project
     *
     * @return the value of mechanics_price.project
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public Integer getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.project
     *
     * @param project the value for mechanics_price.project
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setProject(Integer project) {
        this.project = project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.program
     *
     * @return the value of mechanics_price.program
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public String getProgram() {
        return program;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.program
     *
     * @param program the value for mechanics_price.program
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setProgram(String program) {
        this.program = program;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.node
     *
     * @return the value of mechanics_price.node
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public String getNode() {
        return node;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.node
     *
     * @param node the value for mechanics_price.node
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setNode(String node) {
        this.node = node;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.iprocedure
     *
     * @return the value of mechanics_price.iprocedure
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public String getIprocedure() {
        return iprocedure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.iprocedure
     *
     * @param iprocedure the value for mechanics_price.iprocedure
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setIprocedure(String iprocedure) {
        this.iprocedure = iprocedure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.mechanic
     *
     * @return the value of mechanics_price.mechanic
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public Integer getMechanic() {
        return mechanic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.mechanic
     *
     * @param mechanic the value for mechanics_price.mechanic
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setMechanic(Integer mechanic) {
        this.mechanic = mechanic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.mechanic_name
     *
     * @return the value of mechanics_price.mechanic_name
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public String getMechanicName() {
        return mechanicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.mechanic_name
     *
     * @param mechanicName the value for mechanics_price.mechanic_name
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setMechanicName(String mechanicName) {
        this.mechanicName = mechanicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.driver_name
     *
     * @return the value of mechanics_price.driver_name
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.driver_name
     *
     * @param driverName the value for mechanics_price.driver_name
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.plate_number
     *
     * @return the value of mechanics_price.plate_number
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.plate_number
     *
     * @param plateNumber the value for mechanics_price.plate_number
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.base_type
     *
     * @return the value of mechanics_price.base_type
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public String getBaseType() {
        return baseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.base_type
     *
     * @param baseType the value for mechanics_price.base_type
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setBaseType(String baseType) {
        this.baseType = baseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.icount
     *
     * @return the value of mechanics_price.icount
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public Integer getIcount() {
        return icount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.icount
     *
     * @param icount the value for mechanics_price.icount
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setIcount(Integer icount) {
        this.icount = icount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.unit_price
     *
     * @return the value of mechanics_price.unit_price
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public Integer getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.unit_price
     *
     * @param unitPrice the value for mechanics_price.unit_price
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setUnitPrice(Integer unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.unit_price_type
     *
     * @return the value of mechanics_price.unit_price_type
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public String getUnitPriceType() {
        return unitPriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.unit_price_type
     *
     * @param unitPriceType the value for mechanics_price.unit_price_type
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setUnitPriceType(String unitPriceType) {
        this.unitPriceType = unitPriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.date
     *
     * @return the value of mechanics_price.date
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.date
     *
     * @param date the value for mechanics_price.date
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.create_date
     *
     * @return the value of mechanics_price.create_date
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.create_date
     *
     * @param createDate the value for mechanics_price.create_date
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.staff_name
     *
     * @return the value of mechanics_price.staff_name
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.staff_name
     *
     * @param staffName the value for mechanics_price.staff_name
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.staff
     *
     * @return the value of mechanics_price.staff
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public Integer getStaff() {
        return staff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.staff
     *
     * @param staff the value for mechanics_price.staff
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setStaff(Integer staff) {
        this.staff = staff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.price
     *
     * @return the value of mechanics_price.price
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.price
     *
     * @param price the value for mechanics_price.price
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanics_price.remark
     *
     * @return the value of mechanics_price.remark
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanics_price.remark
     *
     * @param remark the value for mechanics_price.remark
     *
     * @mbg.generated Thu Jan 25 10:11:12 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}