package com.core.entity;

public class RoleMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.id
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.role
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.menu
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    private Integer menu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.order_num
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    private Integer orderNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.id
     *
     * @return the value of role_menu.id
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.id
     *
     * @param id the value for role_menu.id
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.role
     *
     * @return the value of role_menu.role
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.role
     *
     * @param role the value for role_menu.role
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.menu
     *
     * @return the value of role_menu.menu
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    public Integer getMenu() {
        return menu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.menu
     *
     * @param menu the value for role_menu.menu
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    public void setMenu(Integer menu) {
        this.menu = menu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.order_num
     *
     * @return the value of role_menu.order_num
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.order_num
     *
     * @param orderNum the value for role_menu.order_num
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }
}