package com.core.entity;

public class SkipMaterialPriceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skip_material_price.id
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skip_material_price.unit_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    private Integer unitPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skip_material_price.id
     *
     * @return the value of skip_material_price.id
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skip_material_price.id
     *
     * @param id the value for skip_material_price.id
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skip_material_price.unit_price
     *
     * @return the value of skip_material_price.unit_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    public Integer getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skip_material_price.unit_price
     *
     * @param unitPrice the value for skip_material_price.unit_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    public void setUnitPrice(Integer unitPrice) {
        this.unitPrice = unitPrice;
    }
}