package com.core.entity;

public class UnitTypeCombination {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit_type_combination.id
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit_type_combination.base_type
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    private Integer baseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit_type_combination.material_spec
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    private Integer materialSpec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit_type_combination.base_price_type
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    private Integer basePriceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit_type_combination.material_type
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    private Integer materialType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit_type_combination.remark
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit_type_combination.id
     *
     * @return the value of unit_type_combination.id
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit_type_combination.id
     *
     * @param id the value for unit_type_combination.id
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit_type_combination.base_type
     *
     * @return the value of unit_type_combination.base_type
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    public Integer getBaseType() {
        return baseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit_type_combination.base_type
     *
     * @param baseType the value for unit_type_combination.base_type
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    public void setBaseType(Integer baseType) {
        this.baseType = baseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit_type_combination.material_spec
     *
     * @return the value of unit_type_combination.material_spec
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    public Integer getMaterialSpec() {
        return materialSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit_type_combination.material_spec
     *
     * @param materialSpec the value for unit_type_combination.material_spec
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    public void setMaterialSpec(Integer materialSpec) {
        this.materialSpec = materialSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit_type_combination.base_price_type
     *
     * @return the value of unit_type_combination.base_price_type
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    public Integer getBasePriceType() {
        return basePriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit_type_combination.base_price_type
     *
     * @param basePriceType the value for unit_type_combination.base_price_type
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    public void setBasePriceType(Integer basePriceType) {
        this.basePriceType = basePriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit_type_combination.material_type
     *
     * @return the value of unit_type_combination.material_type
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    public Integer getMaterialType() {
        return materialType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit_type_combination.material_type
     *
     * @param materialType the value for unit_type_combination.material_type
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    public void setMaterialType(Integer materialType) {
        this.materialType = materialType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit_type_combination.remark
     *
     * @return the value of unit_type_combination.remark
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit_type_combination.remark
     *
     * @param remark the value for unit_type_combination.remark
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}