package com.core.entity;

public class Xianghan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.id
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.project
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private Integer project;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.node
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private Integer node;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.childNode
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private Integer childnode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col2
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col3
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col4
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col5
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col6
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col7
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col8
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col9
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col10
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col11
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col12
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col13
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col14
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col15
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col16
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col16;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col17
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col18
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col18;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col19
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col20
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col21
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col21;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col22
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col23
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col24
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col25
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col25;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.col26
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String col26;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.create_date
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xianghan.remark
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.id
     *
     * @return the value of xianghan.id
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.id
     *
     * @param id the value for xianghan.id
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.project
     *
     * @return the value of xianghan.project
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public Integer getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.project
     *
     * @param project the value for xianghan.project
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setProject(Integer project) {
        this.project = project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.node
     *
     * @return the value of xianghan.node
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public Integer getNode() {
        return node;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.node
     *
     * @param node the value for xianghan.node
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setNode(Integer node) {
        this.node = node;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.childNode
     *
     * @return the value of xianghan.childNode
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public Integer getChildnode() {
        return childnode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.childNode
     *
     * @param childnode the value for xianghan.childNode
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setChildnode(Integer childnode) {
        this.childnode = childnode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col2
     *
     * @return the value of xianghan.col2
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol2() {
        return col2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col2
     *
     * @param col2 the value for xianghan.col2
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol2(String col2) {
        this.col2 = col2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col3
     *
     * @return the value of xianghan.col3
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol3() {
        return col3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col3
     *
     * @param col3 the value for xianghan.col3
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol3(String col3) {
        this.col3 = col3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col4
     *
     * @return the value of xianghan.col4
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol4() {
        return col4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col4
     *
     * @param col4 the value for xianghan.col4
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol4(String col4) {
        this.col4 = col4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col5
     *
     * @return the value of xianghan.col5
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol5() {
        return col5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col5
     *
     * @param col5 the value for xianghan.col5
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol5(String col5) {
        this.col5 = col5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col6
     *
     * @return the value of xianghan.col6
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol6() {
        return col6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col6
     *
     * @param col6 the value for xianghan.col6
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol6(String col6) {
        this.col6 = col6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col7
     *
     * @return the value of xianghan.col7
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol7() {
        return col7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col7
     *
     * @param col7 the value for xianghan.col7
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol7(String col7) {
        this.col7 = col7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col8
     *
     * @return the value of xianghan.col8
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol8() {
        return col8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col8
     *
     * @param col8 the value for xianghan.col8
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol8(String col8) {
        this.col8 = col8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col9
     *
     * @return the value of xianghan.col9
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol9() {
        return col9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col9
     *
     * @param col9 the value for xianghan.col9
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol9(String col9) {
        this.col9 = col9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col10
     *
     * @return the value of xianghan.col10
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol10() {
        return col10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col10
     *
     * @param col10 the value for xianghan.col10
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol10(String col10) {
        this.col10 = col10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col11
     *
     * @return the value of xianghan.col11
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol11() {
        return col11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col11
     *
     * @param col11 the value for xianghan.col11
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol11(String col11) {
        this.col11 = col11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col12
     *
     * @return the value of xianghan.col12
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol12() {
        return col12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col12
     *
     * @param col12 the value for xianghan.col12
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol12(String col12) {
        this.col12 = col12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col13
     *
     * @return the value of xianghan.col13
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol13() {
        return col13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col13
     *
     * @param col13 the value for xianghan.col13
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol13(String col13) {
        this.col13 = col13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col14
     *
     * @return the value of xianghan.col14
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol14() {
        return col14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col14
     *
     * @param col14 the value for xianghan.col14
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol14(String col14) {
        this.col14 = col14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col15
     *
     * @return the value of xianghan.col15
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol15() {
        return col15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col15
     *
     * @param col15 the value for xianghan.col15
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol15(String col15) {
        this.col15 = col15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col16
     *
     * @return the value of xianghan.col16
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol16() {
        return col16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col16
     *
     * @param col16 the value for xianghan.col16
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol16(String col16) {
        this.col16 = col16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col17
     *
     * @return the value of xianghan.col17
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol17() {
        return col17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col17
     *
     * @param col17 the value for xianghan.col17
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol17(String col17) {
        this.col17 = col17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col18
     *
     * @return the value of xianghan.col18
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol18() {
        return col18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col18
     *
     * @param col18 the value for xianghan.col18
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol18(String col18) {
        this.col18 = col18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col19
     *
     * @return the value of xianghan.col19
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol19() {
        return col19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col19
     *
     * @param col19 the value for xianghan.col19
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol19(String col19) {
        this.col19 = col19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col20
     *
     * @return the value of xianghan.col20
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol20() {
        return col20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col20
     *
     * @param col20 the value for xianghan.col20
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol20(String col20) {
        this.col20 = col20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col21
     *
     * @return the value of xianghan.col21
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol21() {
        return col21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col21
     *
     * @param col21 the value for xianghan.col21
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol21(String col21) {
        this.col21 = col21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col22
     *
     * @return the value of xianghan.col22
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol22() {
        return col22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col22
     *
     * @param col22 the value for xianghan.col22
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol22(String col22) {
        this.col22 = col22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col23
     *
     * @return the value of xianghan.col23
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol23() {
        return col23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col23
     *
     * @param col23 the value for xianghan.col23
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol23(String col23) {
        this.col23 = col23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col24
     *
     * @return the value of xianghan.col24
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol24() {
        return col24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col24
     *
     * @param col24 the value for xianghan.col24
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol24(String col24) {
        this.col24 = col24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col25
     *
     * @return the value of xianghan.col25
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol25() {
        return col25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col25
     *
     * @param col25 the value for xianghan.col25
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol25(String col25) {
        this.col25 = col25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.col26
     *
     * @return the value of xianghan.col26
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCol26() {
        return col26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.col26
     *
     * @param col26 the value for xianghan.col26
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCol26(String col26) {
        this.col26 = col26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.create_date
     *
     * @return the value of xianghan.create_date
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.create_date
     *
     * @param createDate the value for xianghan.create_date
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xianghan.remark
     *
     * @return the value of xianghan.remark
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xianghan.remark
     *
     * @param remark the value for xianghan.remark
     *
     * @mbg.generated Wed Jan 17 19:31:18 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}