package com.core.entity.main;

public class Enterprise {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.id
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.name
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.serial_number
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private String serialNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.password
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.legal_person_idcard
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private String legalPersonIdcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.mobile
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.create_date
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.tip_date
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private Integer tipDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.code
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.web_name
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private String webName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.database_name
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private String databaseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.remark
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.id
     *
     * @return the value of enterprise.id
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.id
     *
     * @param id the value for enterprise.id
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.name
     *
     * @return the value of enterprise.name
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.name
     *
     * @param name the value for enterprise.name
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.serial_number
     *
     * @return the value of enterprise.serial_number
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.serial_number
     *
     * @param serialNumber the value for enterprise.serial_number
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.password
     *
     * @return the value of enterprise.password
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.password
     *
     * @param password the value for enterprise.password
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.legal_person_idcard
     *
     * @return the value of enterprise.legal_person_idcard
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public String getLegalPersonIdcard() {
        return legalPersonIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.legal_person_idcard
     *
     * @param legalPersonIdcard the value for enterprise.legal_person_idcard
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setLegalPersonIdcard(String legalPersonIdcard) {
        this.legalPersonIdcard = legalPersonIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.mobile
     *
     * @return the value of enterprise.mobile
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.mobile
     *
     * @param mobile the value for enterprise.mobile
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.create_date
     *
     * @return the value of enterprise.create_date
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.create_date
     *
     * @param createDate the value for enterprise.create_date
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.tip_date
     *
     * @return the value of enterprise.tip_date
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public Integer getTipDate() {
        return tipDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.tip_date
     *
     * @param tipDate the value for enterprise.tip_date
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setTipDate(Integer tipDate) {
        this.tipDate = tipDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.code
     *
     * @return the value of enterprise.code
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.code
     *
     * @param code the value for enterprise.code
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.web_name
     *
     * @return the value of enterprise.web_name
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public String getWebName() {
        return webName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.web_name
     *
     * @param webName the value for enterprise.web_name
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setWebName(String webName) {
        this.webName = webName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.database_name
     *
     * @return the value of enterprise.database_name
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public String getDatabaseName() {
        return databaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.database_name
     *
     * @param databaseName the value for enterprise.database_name
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setDatabaseName(String databaseName) {
        this.databaseName = databaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.remark
     *
     * @return the value of enterprise.remark
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.remark
     *
     * @param remark the value for enterprise.remark
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}