package com.core.entity.main;

public class EnterpriseMeal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_meal.id
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_meal.enterprise
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private Integer enterprise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_meal.meal
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private Integer meal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_meal.expiry_date
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private Integer expiryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_meal.state
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_meal.id
     *
     * @return the value of enterprise_meal.id
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_meal.id
     *
     * @param id the value for enterprise_meal.id
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_meal.enterprise
     *
     * @return the value of enterprise_meal.enterprise
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public Integer getEnterprise() {
        return enterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_meal.enterprise
     *
     * @param enterprise the value for enterprise_meal.enterprise
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setEnterprise(Integer enterprise) {
        this.enterprise = enterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_meal.meal
     *
     * @return the value of enterprise_meal.meal
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public Integer getMeal() {
        return meal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_meal.meal
     *
     * @param meal the value for enterprise_meal.meal
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setMeal(Integer meal) {
        this.meal = meal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_meal.expiry_date
     *
     * @return the value of enterprise_meal.expiry_date
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public Integer getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_meal.expiry_date
     *
     * @param expiryDate the value for enterprise_meal.expiry_date
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setExpiryDate(Integer expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_meal.state
     *
     * @return the value of enterprise_meal.state
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_meal.state
     *
     * @param state the value for enterprise_meal.state
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }
}