package com.core.entity.main;

public class Module {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.id
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.name
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.remark
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.id
     *
     * @return the value of module.id
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.id
     *
     * @param id the value for module.id
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.name
     *
     * @return the value of module.name
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.name
     *
     * @param name the value for module.name
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.remark
     *
     * @return the value of module.remark
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.remark
     *
     * @param remark the value for module.remark
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}