package com.core.mapper;

import com.core.entity.DayBook;
import com.core.entity.DayBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface DayBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_book
     *
     * @mbg.generated Fri Jan 12 21:08:26 CST 2018
     */
    @SelectProvider(type=DayBookSqlProvider.class, method="countByExample")
    long countByExample(DayBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_book
     *
     * @mbg.generated Fri Jan 12 21:08:26 CST 2018
     */
    @DeleteProvider(type=DayBookSqlProvider.class, method="deleteByExample")
    int deleteByExample(DayBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_book
     *
     * @mbg.generated Fri Jan 12 21:08:26 CST 2018
     */
    @Delete({
        "delete from day_book",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_book
     *
     * @mbg.generated Fri Jan 12 21:08:26 CST 2018
     */
    @Options(useGeneratedKeys=true)
    @Insert({
        "insert into day_book (id, project, ",
        "voucherno, income, ",
        "account, income_type, ",
        "create_date, date, ",
        "pay, pay_for, presenter, ",
        "summary, bill_type, ",
        "department, remark)",
        "values (#{id,jdbcType=INTEGER}, #{project,jdbcType=INTEGER}, ",
        "#{voucherno,jdbcType=VARCHAR}, #{income,jdbcType=INTEGER}, ",
        "#{account,jdbcType=VARCHAR}, #{incomeType,jdbcType=INTEGER}, ",
        "#{createDate,jdbcType=VARCHAR}, #{date,jdbcType=VARCHAR}, ",
        "#{pay,jdbcType=INTEGER}, #{payFor,jdbcType=VARCHAR}, #{presenter,jdbcType=VARCHAR}, ",
        "#{summary,jdbcType=VARCHAR}, #{billType,jdbcType=INTEGER}, ",
        "#{department,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(DayBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_book
     *
     * @mbg.generated Fri Jan 12 21:08:26 CST 2018
     */
    @Options(useGeneratedKeys=true)
    @InsertProvider(type=DayBookSqlProvider.class, method="insertSelective")
    int insertSelective(DayBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_book
     *
     * @mbg.generated Fri Jan 12 21:08:26 CST 2018
     */
    @SelectProvider(type=DayBookSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="project", property="project", jdbcType=JdbcType.INTEGER),
        @Result(column="voucherno", property="voucherno", jdbcType=JdbcType.VARCHAR),
        @Result(column="income", property="income", jdbcType=JdbcType.INTEGER),
        @Result(column="account", property="account", jdbcType=JdbcType.VARCHAR),
        @Result(column="income_type", property="incomeType", jdbcType=JdbcType.INTEGER),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="date", property="date", jdbcType=JdbcType.VARCHAR),
        @Result(column="pay", property="pay", jdbcType=JdbcType.INTEGER),
        @Result(column="pay_for", property="payFor", jdbcType=JdbcType.VARCHAR),
        @Result(column="presenter", property="presenter", jdbcType=JdbcType.VARCHAR),
        @Result(column="summary", property="summary", jdbcType=JdbcType.VARCHAR),
        @Result(column="bill_type", property="billType", jdbcType=JdbcType.INTEGER),
        @Result(column="department", property="department", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<DayBook> selectByExample(DayBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_book
     *
     * @mbg.generated Fri Jan 12 21:08:26 CST 2018
     */
    @Select({
        "select",
        "id, project, voucherno, income, account, income_type, create_date, date, pay, ",
        "pay_for, presenter, summary, bill_type, department, remark",
        "from day_book",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="project", property="project", jdbcType=JdbcType.INTEGER),
        @Result(column="voucherno", property="voucherno", jdbcType=JdbcType.VARCHAR),
        @Result(column="income", property="income", jdbcType=JdbcType.INTEGER),
        @Result(column="account", property="account", jdbcType=JdbcType.VARCHAR),
        @Result(column="income_type", property="incomeType", jdbcType=JdbcType.INTEGER),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="date", property="date", jdbcType=JdbcType.VARCHAR),
        @Result(column="pay", property="pay", jdbcType=JdbcType.INTEGER),
        @Result(column="pay_for", property="payFor", jdbcType=JdbcType.VARCHAR),
        @Result(column="presenter", property="presenter", jdbcType=JdbcType.VARCHAR),
        @Result(column="summary", property="summary", jdbcType=JdbcType.VARCHAR),
        @Result(column="bill_type", property="billType", jdbcType=JdbcType.INTEGER),
        @Result(column="department", property="department", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    DayBook selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_book
     *
     * @mbg.generated Fri Jan 12 21:08:26 CST 2018
     */
    @UpdateProvider(type=DayBookSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") DayBook record, @Param("example") DayBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_book
     *
     * @mbg.generated Fri Jan 12 21:08:26 CST 2018
     */
    @UpdateProvider(type=DayBookSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") DayBook record, @Param("example") DayBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_book
     *
     * @mbg.generated Fri Jan 12 21:08:26 CST 2018
     */
    @UpdateProvider(type=DayBookSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(DayBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_book
     *
     * @mbg.generated Fri Jan 12 21:08:26 CST 2018
     */
    @Update({
        "update day_book",
        "set project = #{project,jdbcType=INTEGER},",
          "voucherno = #{voucherno,jdbcType=VARCHAR},",
          "income = #{income,jdbcType=INTEGER},",
          "account = #{account,jdbcType=VARCHAR},",
          "income_type = #{incomeType,jdbcType=INTEGER},",
          "create_date = #{createDate,jdbcType=VARCHAR},",
          "date = #{date,jdbcType=VARCHAR},",
          "pay = #{pay,jdbcType=INTEGER},",
          "pay_for = #{payFor,jdbcType=VARCHAR},",
          "presenter = #{presenter,jdbcType=VARCHAR},",
          "summary = #{summary,jdbcType=VARCHAR},",
          "bill_type = #{billType,jdbcType=INTEGER},",
          "department = #{department,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(DayBook record);
}