package com.core.mapper;

import com.core.entity.Foreman;
import com.core.entity.ForemanExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ForemanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreman
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    @SelectProvider(type=ForemanSqlProvider.class, method="countByExample")
    long countByExample(ForemanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreman
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    @DeleteProvider(type=ForemanSqlProvider.class, method="deleteByExample")
    int deleteByExample(ForemanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreman
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    @Delete({
        "delete from ${database}.foreman",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("database") String database,@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreman
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    @Options(useGeneratedKeys=true)
    @Insert({
        "insert into foreman (id, code, ",
        "name, type, password, ",
        "idcard, mobile, ",
        "create_date, remark)",
        "values (#{id,jdbcType=INTEGER}, #{code,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, #{password,jdbcType=VARCHAR}, ",
        "#{idcard,jdbcType=VARCHAR}, #{mobile,jdbcType=VARCHAR}, ",
        "#{createDate,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(Foreman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreman
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    @Options(useGeneratedKeys=true)
    @InsertProvider(type=ForemanSqlProvider.class, method="insertSelective")
    int insertSelective(Foreman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreman
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    @SelectProvider(type=ForemanSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="idcard", property="idcard", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<Foreman> selectByExample(ForemanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreman
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    @Select({
        "select",
        "id, code, name, type, password, idcard, mobile, create_date, remark",
        "from ${database}.foreman",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="idcard", property="idcard", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    Foreman selectByPrimaryKey(@Param("database") String database, @Param("id")Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreman
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    @UpdateProvider(type=ForemanSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Foreman record, @Param("example") ForemanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreman
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    @UpdateProvider(type=ForemanSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Foreman record, @Param("example") ForemanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreman
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    @UpdateProvider(type=ForemanSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Foreman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreman
     *
     * @mbg.generated Thu Dec 21 16:51:25 CST 2017
     */
    @Update({
        "update foreman",
        "set code = #{code,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "password = #{password,jdbcType=VARCHAR},",
          "idcard = #{idcard,jdbcType=VARCHAR},",
          "mobile = #{mobile,jdbcType=VARCHAR},",
          "create_date = #{createDate,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Foreman record);
}