package com.core.mapper;

import com.core.entity.Gaibanhan;
import com.core.entity.GaibanhanExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface GaibanhanMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	@SelectProvider(type = GaibanhanSqlProvider.class, method = "countByExample")
	long countByExample(GaibanhanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	@DeleteProvider(type = GaibanhanSqlProvider.class, method = "deleteByExample")
	int deleteByExample(GaibanhanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	@Delete({ "delete from gaibanhan", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	@Insert({ "insert into gaibanhan (id, project, ", "node, childNode, ", "col2, col3, col4, ", "col5, col6, col7, ",
			"col8, col9, create_date, ", "remark)", "values (#{id,jdbcType=INTEGER}, #{project,jdbcType=INTEGER}, ",
			"#{node,jdbcType=INTEGER}, #{childnode,jdbcType=INTEGER}, ",
			"#{col2,jdbcType=VARCHAR}, #{col3,jdbcType=VARCHAR}, #{col4,jdbcType=VARCHAR}, ",
			"#{col5,jdbcType=VARCHAR}, #{col6,jdbcType=VARCHAR}, #{col7,jdbcType=VARCHAR}, ",
			"#{col8,jdbcType=VARCHAR}, #{col9,jdbcType=VARCHAR}, #{createDate,jdbcType=VARCHAR}, ",
			"#{remark,jdbcType=VARCHAR})" })
	int insert(Gaibanhan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	@Options(useGeneratedKeys = true)
	@InsertProvider(type = GaibanhanSqlProvider.class, method = "insertSelective")
	int insertSelective(Gaibanhan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	@SelectProvider(type = GaibanhanSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "project", property = "project", jdbcType = JdbcType.INTEGER),
			@Result(column = "node", property = "node", jdbcType = JdbcType.INTEGER),
			@Result(column = "childNode", property = "childnode", jdbcType = JdbcType.INTEGER),
			@Result(column = "col2", property = "col2", jdbcType = JdbcType.VARCHAR),
			@Result(column = "col3", property = "col3", jdbcType = JdbcType.VARCHAR),
			@Result(column = "col4", property = "col4", jdbcType = JdbcType.VARCHAR),
			@Result(column = "col5", property = "col5", jdbcType = JdbcType.VARCHAR),
			@Result(column = "col6", property = "col6", jdbcType = JdbcType.VARCHAR),
			@Result(column = "col7", property = "col7", jdbcType = JdbcType.VARCHAR),
			@Result(column = "col8", property = "col8", jdbcType = JdbcType.VARCHAR),
			@Result(column = "col9", property = "col9", jdbcType = JdbcType.VARCHAR),
			@Result(column = "create_date", property = "createDate", jdbcType = JdbcType.VARCHAR),
			@Result(column = "remark", property = "remark", jdbcType = JdbcType.VARCHAR) })
	List<Gaibanhan> selectByExample(GaibanhanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	@Select({ "select", "id, project, node, childNode, col2, col3, col4, col5, col6, col7, col8, col9, ",
			"create_date, remark", "from gaibanhan", "where id = #{id,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "project", property = "project", jdbcType = JdbcType.INTEGER),
			@Result(column = "node", property = "node", jdbcType = JdbcType.INTEGER),
			@Result(column = "childNode", property = "childnode", jdbcType = JdbcType.INTEGER),
			@Result(column = "col2", property = "col2", jdbcType = JdbcType.VARCHAR),
			@Result(column = "col3", property = "col3", jdbcType = JdbcType.VARCHAR),
			@Result(column = "col4", property = "col4", jdbcType = JdbcType.VARCHAR),
			@Result(column = "col5", property = "col5", jdbcType = JdbcType.VARCHAR),
			@Result(column = "col6", property = "col6", jdbcType = JdbcType.VARCHAR),
			@Result(column = "col7", property = "col7", jdbcType = JdbcType.VARCHAR),
			@Result(column = "col8", property = "col8", jdbcType = JdbcType.VARCHAR),
			@Result(column = "col9", property = "col9", jdbcType = JdbcType.VARCHAR),
			@Result(column = "create_date", property = "createDate", jdbcType = JdbcType.VARCHAR),
			@Result(column = "remark", property = "remark", jdbcType = JdbcType.VARCHAR) })
	Gaibanhan selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	@UpdateProvider(type = GaibanhanSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Gaibanhan record, @Param("example") GaibanhanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	@UpdateProvider(type = GaibanhanSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Gaibanhan record, @Param("example") GaibanhanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	@UpdateProvider(type = GaibanhanSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Gaibanhan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	@Update({ "update gaibanhan", "set project = #{project,jdbcType=INTEGER},", "node = #{node,jdbcType=INTEGER},",
			"childNode = #{childnode,jdbcType=INTEGER},", "col2 = #{col2,jdbcType=VARCHAR},",
			"col3 = #{col3,jdbcType=VARCHAR},", "col4 = #{col4,jdbcType=VARCHAR},", "col5 = #{col5,jdbcType=VARCHAR},",
			"col6 = #{col6,jdbcType=VARCHAR},", "col7 = #{col7,jdbcType=VARCHAR},", "col8 = #{col8,jdbcType=VARCHAR},",
			"col9 = #{col9,jdbcType=VARCHAR},", "create_date = #{createDate,jdbcType=VARCHAR},",
			"remark = #{remark,jdbcType=VARCHAR}", "where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Gaibanhan record);
}