package com.core.mapper;

import com.core.entity.Gaibanhan;
import com.core.entity.GaibanhanExample.Criteria;
import com.core.entity.GaibanhanExample.Criterion;
import com.core.util.Utils;
import com.core.entity.GaibanhanExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class GaibanhanSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	public String countByExample(GaibanhanExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("gaibanhan");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	public String deleteByExample(GaibanhanExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM(Utils.getDatabase()+".gaibanhan");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	public String insertSelective(Gaibanhan record) {
		SQL sql = new SQL();
		sql.INSERT_INTO(Utils.getDatabase()+".gaibanhan");
		if (record.getId() != null) {
			sql.VALUES("id", "#{id,jdbcType=INTEGER}");
		}
		if (record.getProject() != null) {
			sql.VALUES("project", "#{project,jdbcType=INTEGER}");
		}
		if (record.getNode() != null) {
			sql.VALUES("node", "#{node,jdbcType=INTEGER}");
		}
		if (record.getChildnode() != null) {
			sql.VALUES("childNode", "#{childnode,jdbcType=INTEGER}");
		}
		if (record.getCol2() != null) {
			sql.VALUES("col2", "#{col2,jdbcType=VARCHAR}");
		}
		if (record.getCol3() != null) {
			sql.VALUES("col3", "#{col3,jdbcType=VARCHAR}");
		}
		if (record.getCol4() != null) {
			sql.VALUES("col4", "#{col4,jdbcType=VARCHAR}");
		}
		if (record.getCol5() != null) {
			sql.VALUES("col5", "#{col5,jdbcType=VARCHAR}");
		}
		if (record.getCol6() != null) {
			sql.VALUES("col6", "#{col6,jdbcType=VARCHAR}");
		}
		if (record.getCol7() != null) {
			sql.VALUES("col7", "#{col7,jdbcType=VARCHAR}");
		}
		if (record.getCol8() != null) {
			sql.VALUES("col8", "#{col8,jdbcType=VARCHAR}");
		}
		if (record.getCol9() != null) {
			sql.VALUES("col9", "#{col9,jdbcType=VARCHAR}");
		}
		if (record.getCreateDate() != null) {
			sql.VALUES("create_date", "#{createDate,jdbcType=VARCHAR}");
		}
		if (record.getRemark() != null) {
			sql.VALUES("remark", "#{remark,jdbcType=VARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	public String selectByExample(GaibanhanExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id");
		} else {
			sql.SELECT("id");
		}
		sql.SELECT("project");
		sql.SELECT("node");
		sql.SELECT("childNode");
		sql.SELECT("col2");
		sql.SELECT("col3");
		sql.SELECT("col4");
		sql.SELECT("col5");
		sql.SELECT("col6");
		sql.SELECT("col7");
		sql.SELECT("col8");
		sql.SELECT("col9");
		sql.SELECT("create_date");
		sql.SELECT("remark");
		sql.FROM(Utils.getDatabase()+".gaibanhan");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		Gaibanhan record = (Gaibanhan) parameter.get("record");
		GaibanhanExample example = (GaibanhanExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("gaibanhan");
		if (record.getId() != null) {
			sql.SET("id = #{record.id,jdbcType=INTEGER}");
		}
		if (record.getProject() != null) {
			sql.SET("project = #{record.project,jdbcType=INTEGER}");
		}
		if (record.getNode() != null) {
			sql.SET("node = #{record.node,jdbcType=INTEGER}");
		}
		if (record.getChildnode() != null) {
			sql.SET("childNode = #{record.childnode,jdbcType=INTEGER}");
		}
		if (record.getCol2() != null) {
			sql.SET("col2 = #{record.col2,jdbcType=VARCHAR}");
		}
		if (record.getCol3() != null) {
			sql.SET("col3 = #{record.col3,jdbcType=VARCHAR}");
		}
		if (record.getCol4() != null) {
			sql.SET("col4 = #{record.col4,jdbcType=VARCHAR}");
		}
		if (record.getCol5() != null) {
			sql.SET("col5 = #{record.col5,jdbcType=VARCHAR}");
		}
		if (record.getCol6() != null) {
			sql.SET("col6 = #{record.col6,jdbcType=VARCHAR}");
		}
		if (record.getCol7() != null) {
			sql.SET("col7 = #{record.col7,jdbcType=VARCHAR}");
		}
		if (record.getCol8() != null) {
			sql.SET("col8 = #{record.col8,jdbcType=VARCHAR}");
		}
		if (record.getCol9() != null) {
			sql.SET("col9 = #{record.col9,jdbcType=VARCHAR}");
		}
		if (record.getCreateDate() != null) {
			sql.SET("create_date = #{record.createDate,jdbcType=VARCHAR}");
		}
		if (record.getRemark() != null) {
			sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("gaibanhan");
		sql.SET("id = #{record.id,jdbcType=INTEGER}");
		sql.SET("project = #{record.project,jdbcType=INTEGER}");
		sql.SET("node = #{record.node,jdbcType=INTEGER}");
		sql.SET("childNode = #{record.childnode,jdbcType=INTEGER}");
		sql.SET("col2 = #{record.col2,jdbcType=VARCHAR}");
		sql.SET("col3 = #{record.col3,jdbcType=VARCHAR}");
		sql.SET("col4 = #{record.col4,jdbcType=VARCHAR}");
		sql.SET("col5 = #{record.col5,jdbcType=VARCHAR}");
		sql.SET("col6 = #{record.col6,jdbcType=VARCHAR}");
		sql.SET("col7 = #{record.col7,jdbcType=VARCHAR}");
		sql.SET("col8 = #{record.col8,jdbcType=VARCHAR}");
		sql.SET("col9 = #{record.col9,jdbcType=VARCHAR}");
		sql.SET("create_date = #{record.createDate,jdbcType=VARCHAR}");
		sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
		GaibanhanExample example = (GaibanhanExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	public String updateByPrimaryKeySelective(Gaibanhan record) {
		SQL sql = new SQL();
		sql.UPDATE(Utils.getDatabase()+".gaibanhan");
		if (record.getProject() != null) {
			sql.SET("project = #{project,jdbcType=INTEGER}");
		}
		if (record.getNode() != null) {
			sql.SET("node = #{node,jdbcType=INTEGER}");
		}
		if (record.getChildnode() != null) {
			sql.SET("childNode = #{childnode,jdbcType=INTEGER}");
		}
		if (record.getCol2() != null) {
			sql.SET("col2 = #{col2,jdbcType=VARCHAR}");
		}
		if (record.getCol3() != null) {
			sql.SET("col3 = #{col3,jdbcType=VARCHAR}");
		}
		if (record.getCol4() != null) {
			sql.SET("col4 = #{col4,jdbcType=VARCHAR}");
		}
		if (record.getCol5() != null) {
			sql.SET("col5 = #{col5,jdbcType=VARCHAR}");
		}
		if (record.getCol6() != null) {
			sql.SET("col6 = #{col6,jdbcType=VARCHAR}");
		}
		if (record.getCol7() != null) {
			sql.SET("col7 = #{col7,jdbcType=VARCHAR}");
		}
		if (record.getCol8() != null) {
			sql.SET("col8 = #{col8,jdbcType=VARCHAR}");
		}
		if (record.getCol9() != null) {
			sql.SET("col9 = #{col9,jdbcType=VARCHAR}");
		}
		if (record.getCreateDate() != null) {
			sql.SET("create_date = #{createDate,jdbcType=VARCHAR}");
		}
		if (record.getRemark() != null) {
			sql.SET("remark = #{remark,jdbcType=VARCHAR}");
		}
		sql.WHERE("id = #{id,jdbcType=INTEGER}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gaibanhan
	 * @mbg.generated  Wed Jan 17 19:31:18 CST 2018
	 */
	protected void applyWhere(SQL sql, GaibanhanExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}