package com.core.mapper;

import com.core.entity.LaborCost;
import com.core.entity.LaborCostExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface LaborCostMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table labor_cost
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@SelectProvider(type = LaborCostSqlProvider.class, method = "countByExample")
	long countByExample(LaborCostExample example);

	
	@SelectProvider(type = LaborCostSqlProvider.class, method = "sumPriceByExample")
	long sumPriceByExample(LaborCostExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table labor_cost
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@DeleteProvider(type = LaborCostSqlProvider.class, method = "deleteByExample")
	int deleteByExample(LaborCostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table labor_cost
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@Delete({ "delete from labor_cost", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table labor_cost
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@Insert({ "insert into labor_cost (id, project, ", "program, node, iprocedure, ", "foreman, foreman_name, ",
			"worker_type, worker, ", "icount, base_type, ", "price, unit_price, ", "unit_price_type, worker_nums, ",
			"create_date, date, ", "staff_name, staff, ", "remark)",
			"values (#{id,jdbcType=INTEGER}, #{project,jdbcType=INTEGER}, ",
			"#{program,jdbcType=VARCHAR}, #{node,jdbcType=VARCHAR}, #{iprocedure,jdbcType=VARCHAR}, ",
			"#{foreman,jdbcType=INTEGER}, #{foremanName,jdbcType=VARCHAR}, ",
			"#{workerType,jdbcType=VARCHAR}, #{worker,jdbcType=INTEGER}, ",
			"#{icount,jdbcType=INTEGER}, #{baseType,jdbcType=VARCHAR}, ",
			"#{price,jdbcType=INTEGER}, #{unitPrice,jdbcType=INTEGER}, ",
			"#{unitPriceType,jdbcType=VARCHAR}, #{workerNums,jdbcType=INTEGER}, ",
			"#{createDate,jdbcType=VARCHAR}, #{date,jdbcType=VARCHAR}, ",
			"#{staffName,jdbcType=VARCHAR}, #{staff,jdbcType=INTEGER}, ", "#{remark,jdbcType=VARCHAR})" })
	int insert(LaborCost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table labor_cost
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@InsertProvider(type = LaborCostSqlProvider.class, method = "insertSelective")
	int insertSelective(LaborCost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table labor_cost
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@SelectProvider(type = LaborCostSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "project", property = "project", jdbcType = JdbcType.INTEGER),
			@Result(column = "program", property = "program", jdbcType = JdbcType.VARCHAR),
			@Result(column = "node", property = "node", jdbcType = JdbcType.VARCHAR),
			@Result(column = "iprocedure", property = "iprocedure", jdbcType = JdbcType.VARCHAR),
			@Result(column = "foreman", property = "foreman", jdbcType = JdbcType.INTEGER),
			@Result(column = "foreman_name", property = "foremanName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "worker_type", property = "workerType", jdbcType = JdbcType.VARCHAR),
			@Result(column = "worker", property = "worker", jdbcType = JdbcType.INTEGER),
			@Result(column = "icount", property = "icount", jdbcType = JdbcType.INTEGER),
			@Result(column = "base_type", property = "baseType", jdbcType = JdbcType.VARCHAR),
			@Result(column = "price", property = "price", jdbcType = JdbcType.INTEGER),
			@Result(column = "unit_price", property = "unitPrice", jdbcType = JdbcType.INTEGER),
			@Result(column = "unit_price_type", property = "unitPriceType", jdbcType = JdbcType.VARCHAR),
			@Result(column = "worker_nums", property = "workerNums", jdbcType = JdbcType.INTEGER),
			@Result(column = "create_date", property = "createDate", jdbcType = JdbcType.VARCHAR),
			@Result(column = "date", property = "date", jdbcType = JdbcType.VARCHAR),
			@Result(column = "staff_name", property = "staffName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "staff", property = "staff", jdbcType = JdbcType.INTEGER),
			@Result(column = "remark", property = "remark", jdbcType = JdbcType.VARCHAR) })
	List<LaborCost> selectByExample(LaborCostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table labor_cost
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@Select({ "select", "id, project, program, node, iprocedure, foreman, foreman_name, worker_type, ",
			"worker, icount, base_type, price, unit_price, unit_price_type, worker_nums, ",
			"create_date, date, staff_name, staff, remark", "from labor_cost", "where id = #{id,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "project", property = "project", jdbcType = JdbcType.INTEGER),
			@Result(column = "program", property = "program", jdbcType = JdbcType.VARCHAR),
			@Result(column = "node", property = "node", jdbcType = JdbcType.VARCHAR),
			@Result(column = "iprocedure", property = "iprocedure", jdbcType = JdbcType.VARCHAR),
			@Result(column = "foreman", property = "foreman", jdbcType = JdbcType.INTEGER),
			@Result(column = "foreman_name", property = "foremanName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "worker_type", property = "workerType", jdbcType = JdbcType.VARCHAR),
			@Result(column = "worker", property = "worker", jdbcType = JdbcType.INTEGER),
			@Result(column = "icount", property = "icount", jdbcType = JdbcType.INTEGER),
			@Result(column = "base_type", property = "baseType", jdbcType = JdbcType.VARCHAR),
			@Result(column = "price", property = "price", jdbcType = JdbcType.INTEGER),
			@Result(column = "unit_price", property = "unitPrice", jdbcType = JdbcType.INTEGER),
			@Result(column = "unit_price_type", property = "unitPriceType", jdbcType = JdbcType.VARCHAR),
			@Result(column = "worker_nums", property = "workerNums", jdbcType = JdbcType.INTEGER),
			@Result(column = "create_date", property = "createDate", jdbcType = JdbcType.VARCHAR),
			@Result(column = "date", property = "date", jdbcType = JdbcType.VARCHAR),
			@Result(column = "staff_name", property = "staffName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "staff", property = "staff", jdbcType = JdbcType.INTEGER),
			@Result(column = "remark", property = "remark", jdbcType = JdbcType.VARCHAR) })
	LaborCost selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table labor_cost
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@UpdateProvider(type = LaborCostSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") LaborCost record, @Param("example") LaborCostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table labor_cost
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@UpdateProvider(type = LaborCostSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") LaborCost record, @Param("example") LaborCostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table labor_cost
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@UpdateProvider(type = LaborCostSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(LaborCost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table labor_cost
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@Update({ "update labor_cost", "set project = #{project,jdbcType=INTEGER},",
			"program = #{program,jdbcType=VARCHAR},", "node = #{node,jdbcType=VARCHAR},",
			"iprocedure = #{iprocedure,jdbcType=VARCHAR},", "foreman = #{foreman,jdbcType=INTEGER},",
			"foreman_name = #{foremanName,jdbcType=VARCHAR},", "worker_type = #{workerType,jdbcType=VARCHAR},",
			"worker = #{worker,jdbcType=INTEGER},", "icount = #{icount,jdbcType=INTEGER},",
			"base_type = #{baseType,jdbcType=VARCHAR},", "price = #{price,jdbcType=INTEGER},",
			"unit_price = #{unitPrice,jdbcType=INTEGER},", "unit_price_type = #{unitPriceType,jdbcType=VARCHAR},",
			"worker_nums = #{workerNums,jdbcType=INTEGER},", "create_date = #{createDate,jdbcType=VARCHAR},",
			"date = #{date,jdbcType=VARCHAR},", "staff_name = #{staffName,jdbcType=VARCHAR},",
			"staff = #{staff,jdbcType=INTEGER},", "remark = #{remark,jdbcType=VARCHAR}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(LaborCost record);
}