package com.core.mapper;

import com.core.entity.LoanInfo;
import com.core.entity.LoanInfoExample;
import com.core.util.model.LoanInfoModel;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface LoanInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table loan_info
	 *
	 * @mbg.generated Thu Dec 28 15:11:52 CST 2017
	 */
	@SelectProvider(type = LoanInfoSqlProvider.class, method = "countByExample")
	long countByExample(LoanInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table loan_info
	 *
	 * @mbg.generated Thu Dec 28 15:11:52 CST 2017
	 */
	@DeleteProvider(type = LoanInfoSqlProvider.class, method = "deleteByExample")
	int deleteByExample(LoanInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table loan_info
	 *
	 * @mbg.generated Thu Dec 28 15:11:52 CST 2017
	 */
	@Delete({ "delete from loan_info", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table loan_info
	 *
	 * @mbg.generated Thu Dec 28 15:11:52 CST 2017
	 */
	@Insert({ "insert into loan_info (id, project, ", "person, price, create_date, ", "date, department, ",
			"presenter, reason, ", "remark)", "values (#{id,jdbcType=INTEGER}, #{project,jdbcType=INTEGER}, ",
			"#{person,jdbcType=VARCHAR}, #{price,jdbcType=INTEGER}, #{createDate,jdbcType=VARCHAR}, ",
			"#{date,jdbcType=VARCHAR}, #{department,jdbcType=INTEGER}, ",
			"#{presenter,jdbcType=VARCHAR}, #{reason,jdbcType=VARCHAR}, ", "#{remark,jdbcType=VARCHAR})" })
	int insert(LoanInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table loan_info
	 *
	 * @mbg.generated Thu Dec 28 15:11:52 CST 2017
	 */
	@InsertProvider(type = LoanInfoSqlProvider.class, method = "insertSelective")
	int insertSelective(LoanInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table loan_info
	 *
	 * @mbg.generated Thu Dec 28 15:11:52 CST 2017
	 */
	@SelectProvider(type = LoanInfoSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "project", property = "project", jdbcType = JdbcType.INTEGER),
			@Result(column = "person", property = "person", jdbcType = JdbcType.VARCHAR),
			@Result(column = "price", property = "price", jdbcType = JdbcType.INTEGER),
			@Result(column = "create_date", property = "createDate", jdbcType = JdbcType.VARCHAR),
			@Result(column = "date", property = "date", jdbcType = JdbcType.VARCHAR),
			@Result(column = "department", property = "department", jdbcType = JdbcType.INTEGER),
			@Result(column = "presenter", property = "presenter", jdbcType = JdbcType.VARCHAR),
			@Result(column = "reason", property = "reason", jdbcType = JdbcType.VARCHAR),
			@Result(column = "remark", property = "remark", jdbcType = JdbcType.VARCHAR) })
	List<LoanInfo> selectByExample(LoanInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table loan_info
	 *
	 * @mbg.generated Thu Dec 28 15:11:52 CST 2017
	 */
	@Select({ "select", "id, project, person, price, create_date, date, department, presenter, reason, ", "remark",
			"from loan_info", "where id = #{id,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "project", property = "project", jdbcType = JdbcType.INTEGER),
			@Result(column = "person", property = "person", jdbcType = JdbcType.VARCHAR),
			@Result(column = "price", property = "price", jdbcType = JdbcType.INTEGER),
			@Result(column = "create_date", property = "createDate", jdbcType = JdbcType.VARCHAR),
			@Result(column = "date", property = "date", jdbcType = JdbcType.VARCHAR),
			@Result(column = "department", property = "department", jdbcType = JdbcType.INTEGER),
			@Result(column = "presenter", property = "presenter", jdbcType = JdbcType.VARCHAR),
			@Result(column = "reason", property = "reason", jdbcType = JdbcType.VARCHAR),
			@Result(column = "remark", property = "remark", jdbcType = JdbcType.VARCHAR) })
	LoanInfo selectByPrimaryKey(Integer id);

	@SelectProvider(type = LoanInfoSqlProvider.class, method = "selectModelByExample")
	@Results({ @Result(column = "person", property = "person", jdbcType = JdbcType.VARCHAR),
			@Result(column = "price", property = "price", jdbcType = JdbcType.INTEGER),
			@Result(column = "date", property = "date", jdbcType = JdbcType.VARCHAR),
			@Result(column = "department", property = "department", jdbcType = JdbcType.INTEGER),
			@Result(column = "departmentName", property = "departmentName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "staffName", property = "staffName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "reason", property = "reason", jdbcType = JdbcType.VARCHAR), })
	List<LoanInfoModel> selectModelsByExample(@Param("project") int project);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table loan_info
	 *
	 * @mbg.generated Thu Dec 28 15:11:52 CST 2017
	 */
	@UpdateProvider(type = LoanInfoSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") LoanInfo record, @Param("example") LoanInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table loan_info
	 *
	 * @mbg.generated Thu Dec 28 15:11:52 CST 2017
	 */
	@UpdateProvider(type = LoanInfoSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") LoanInfo record, @Param("example") LoanInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table loan_info
	 *
	 * @mbg.generated Thu Dec 28 15:11:52 CST 2017
	 */
	@UpdateProvider(type = LoanInfoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(LoanInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table loan_info
	 *
	 * @mbg.generated Thu Dec 28 15:11:52 CST 2017
	 */
	@Update({ "update loan_info", "set project = #{project,jdbcType=INTEGER},", "person = #{person,jdbcType=VARCHAR},",
			"price = #{price,jdbcType=INTEGER},", "create_date = #{createDate,jdbcType=VARCHAR},",
			"date = #{date,jdbcType=VARCHAR},", "department = #{department,jdbcType=INTEGER},",
			"presenter = #{presenter,jdbcType=VARCHAR},", "reason = #{reason,jdbcType=VARCHAR},",
			"remark = #{remark,jdbcType=VARCHAR}", "where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(LoanInfo record);
}