package com.core.mapper;

import com.core.entity.MaterialSpec;
import com.core.entity.MaterialSpecExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MaterialSpecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_spec
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @SelectProvider(type=MaterialSpecSqlProvider.class, method="countByExample")
    long countByExample(MaterialSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_spec
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @DeleteProvider(type=MaterialSpecSqlProvider.class, method="deleteByExample")
    int deleteByExample(MaterialSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_spec
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @Delete({
        "delete from material_spec",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_spec
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @Insert({
        "insert into material_spec (id, ms_name, ",
        "ms_order_num, remark, ",
        "material_type)",
        "values (#{id,jdbcType=INTEGER}, #{msName,jdbcType=VARCHAR}, ",
        "#{msOrderNum,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR}, ",
        "#{materialType,jdbcType=INTEGER})"
    })
    int insert(MaterialSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_spec
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @InsertProvider(type=MaterialSpecSqlProvider.class, method="insertSelective")
    int insertSelective(MaterialSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_spec
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @SelectProvider(type=MaterialSpecSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ms_name", property="msName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ms_order_num", property="msOrderNum", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="material_type", property="materialType", jdbcType=JdbcType.INTEGER)
    })
    List<MaterialSpec> selectByExample(MaterialSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_spec
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @Select({
        "select",
        "id, ms_name, ms_order_num, remark, material_type",
        "from ${database}.material_spec",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ms_name", property="msName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ms_order_num", property="msOrderNum", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="material_type", property="materialType", jdbcType=JdbcType.INTEGER)
    })
    MaterialSpec selectByPrimaryKey(@Param("database") String database,@Param("id")Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_spec
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @UpdateProvider(type=MaterialSpecSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MaterialSpec record, @Param("example") MaterialSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_spec
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @UpdateProvider(type=MaterialSpecSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MaterialSpec record, @Param("example") MaterialSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_spec
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @UpdateProvider(type=MaterialSpecSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MaterialSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_spec
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @Update({
        "update material_spec",
        "set ms_name = #{msName,jdbcType=VARCHAR},",
          "ms_order_num = #{msOrderNum,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "material_type = #{materialType,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MaterialSpec record);
}