package com.core.mapper;

import com.core.entity.MaterialType;
import com.core.entity.MaterialTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MaterialTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @SelectProvider(type=MaterialTypeSqlProvider.class, method="countByExample")
    long countByExample(MaterialTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @DeleteProvider(type=MaterialTypeSqlProvider.class, method="deleteByExample")
    int deleteByExample(MaterialTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @Delete({
        "delete from material_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @Insert({
        "insert into material_type (id, mt_name, ",
        "remark, mt_order_num)",
        "values (#{id,jdbcType=INTEGER}, #{mtName,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR}, #{mtOrderNum,jdbcType=INTEGER})"
    })
    int insert(MaterialType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @InsertProvider(type=MaterialTypeSqlProvider.class, method="insertSelective")
    int insertSelective(MaterialType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @SelectProvider(type=MaterialTypeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="mt_name", property="mtName", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="mt_order_num", property="mtOrderNum", jdbcType=JdbcType.INTEGER)
    })
    List<MaterialType> selectByExample(MaterialTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @Select({
        "select",
        "id, mt_name, remark, mt_order_num",
        "from ${database}.material_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="mt_name", property="mtName", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="mt_order_num", property="mtOrderNum", jdbcType=JdbcType.INTEGER)
    })
    MaterialType selectByPrimaryKey(@Param("database")String database,@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @UpdateProvider(type=MaterialTypeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MaterialType record, @Param("example") MaterialTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @UpdateProvider(type=MaterialTypeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MaterialType record, @Param("example") MaterialTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @UpdateProvider(type=MaterialTypeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MaterialType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbg.generated Sun Dec 24 10:27:51 CST 2017
     */
    @Update({
        "update material_type",
        "set mt_name = #{mtName,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "mt_order_num = #{mtOrderNum,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MaterialType record);
}