package com.core.mapper;

import com.core.entity.Material;
import com.core.entity.MaterialExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Sun Dec 24 10:52:47 CST 2017
     */
    @SelectProvider(type=MaterialSqlProvider.class, method="countByExample")
    long countByExample(MaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Sun Dec 24 10:52:47 CST 2017
     */
    @DeleteProvider(type=MaterialSqlProvider.class, method="deleteByExample")
    int deleteByExample(MaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Sun Dec 24 10:52:47 CST 2017
     */
    @Delete({
        "delete from ${database}.material",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("database")String database,@Param("id")Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Sun Dec 24 10:52:47 CST 2017
     */
    @Insert({
        "insert into material (id, project, ",
        "supplier, unit_price, ",
        "unit_price_type, create_date, ",
        "update_date, m_address, ",
        "type, remark)",
        "values (#{id,jdbcType=INTEGER}, #{project,jdbcType=INTEGER}, ",
        "#{supplier,jdbcType=INTEGER}, #{unitPrice,jdbcType=INTEGER}, ",
        "#{unitPriceType,jdbcType=INTEGER}, #{createDate,jdbcType=VARCHAR}, ",
        "#{updateDate,jdbcType=VARCHAR}, #{mAddress,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Sun Dec 24 10:52:47 CST 2017
     */
    @Options(useGeneratedKeys=true)
    @InsertProvider(type=MaterialSqlProvider.class, method="insertSelective")
    int insertSelective(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Sun Dec 24 10:52:47 CST 2017
     */
    @SelectProvider(type=MaterialSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="project", property="project", jdbcType=JdbcType.INTEGER),
        @Result(column="supplier", property="supplier", jdbcType=JdbcType.INTEGER),
        @Result(column="unit_price", property="unitPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="unit_price_type", property="unitPriceType", jdbcType=JdbcType.INTEGER),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="m_address", property="mAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<Material> selectByExample(MaterialExample example);

    
    
    @SelectProvider(type=MaterialSqlProvider.class, method="selectBySql")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="project", property="project", jdbcType=JdbcType.INTEGER),
        @Result(column="supplier", property="supplier", jdbcType=JdbcType.INTEGER),
        @Result(column="unit_price", property="unitPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="unit_price_type", property="unitPriceType", jdbcType=JdbcType.INTEGER),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="m_address", property="mAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<Material> selectBySql(@Param("project")int project);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Sun Dec 24 10:52:47 CST 2017
     */
    @Select({
        "select",
        "id, project, supplier, unit_price, unit_price_type, create_date, update_date, ",
        "m_address, type, remark",
        "from material",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="project", property="project", jdbcType=JdbcType.INTEGER),
        @Result(column="supplier", property="supplier", jdbcType=JdbcType.INTEGER),
        @Result(column="unit_price", property="unitPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="unit_price_type", property="unitPriceType", jdbcType=JdbcType.INTEGER),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="m_address", property="mAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    Material selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Sun Dec 24 10:52:47 CST 2017
     */
    @UpdateProvider(type=MaterialSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Material record, @Param("example") MaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Sun Dec 24 10:52:47 CST 2017
     */
    @UpdateProvider(type=MaterialSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Material record, @Param("example") MaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Sun Dec 24 10:52:47 CST 2017
     */
    @UpdateProvider(type=MaterialSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated Sun Dec 24 10:52:47 CST 2017
     */
    @Update({
        "update material",
        "set project = #{project,jdbcType=INTEGER},",
          "supplier = #{supplier,jdbcType=INTEGER},",
          "unit_price = #{unitPrice,jdbcType=INTEGER},",
          "unit_price_type = #{unitPriceType,jdbcType=INTEGER},",
          "create_date = #{createDate,jdbcType=VARCHAR},",
          "update_date = #{updateDate,jdbcType=VARCHAR},",
          "m_address = #{mAddress,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Material record);
}