package com.core.mapper;

import com.core.entity.MaterialReceived;
import com.core.entity.MaterialReceivedExample;
import com.core.util.model.chart.MaterialChartModel;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MaterialReceivedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_received
     *
     * @mbg.generated Sun Jan 28 21:12:17 CST 2018
     */
    @SelectProvider(type=MaterialReceivedSqlProvider.class, method="countByExample")
    long countByExample(MaterialReceivedExample example);
    
    @SelectProvider(type=MaterialReceivedSqlProvider.class, method="sumMaterialPriceByExample")
    long sumMaterialPriceByExample(MaterialReceivedExample example);
   
    @SelectProvider(type=MaterialReceivedSqlProvider.class, method="sumFreightPriceByExample")
    long sumFreightPriceByExample(MaterialReceivedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_received
     *
     * @mbg.generated Sun Jan 28 21:12:17 CST 2018
     */
    @DeleteProvider(type=MaterialReceivedSqlProvider.class, method="deleteByExample")
    int deleteByExample(MaterialReceivedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_received
     *
     * @mbg.generated Sun Jan 28 21:12:17 CST 2018
     */
    @Delete({
        "delete from material_received",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_received
     *
     * @mbg.generated Sun Jan 28 21:12:17 CST 2018
     */
    @Insert({
        "insert into material_received (id, project, ",
        "node, program, iprocedure, ",
        "mechainc, supplier, ",
        "supplier_name, material, ",
        "plate_number, icount, ",
        "base_type, material_spec, ",
        "distance, material_price, ",
        "create_date, date, ",
        "unit_price, material_name, ",
        "unit_freight_price, freight_price, ",
        "staff_name, staff, ",
        "remark)",
        "values (#{id,jdbcType=INTEGER}, #{project,jdbcType=INTEGER}, ",
        "#{node,jdbcType=VARCHAR}, #{program,jdbcType=VARCHAR}, #{iprocedure,jdbcType=VARCHAR}, ",
        "#{mechainc,jdbcType=INTEGER}, #{supplier,jdbcType=INTEGER}, ",
        "#{supplierName,jdbcType=VARCHAR}, #{material,jdbcType=INTEGER}, ",
        "#{plateNumber,jdbcType=VARCHAR}, #{icount,jdbcType=INTEGER}, ",
        "#{baseType,jdbcType=VARCHAR}, #{materialSpec,jdbcType=VARCHAR}, ",
        "#{distance,jdbcType=INTEGER}, #{materialPrice,jdbcType=INTEGER}, ",
        "#{createDate,jdbcType=VARCHAR}, #{date,jdbcType=VARCHAR}, ",
        "#{unitPrice,jdbcType=INTEGER}, #{materialName,jdbcType=VARCHAR}, ",
        "#{unitFreightPrice,jdbcType=INTEGER}, #{freightPrice,jdbcType=INTEGER}, ",
        "#{staffName,jdbcType=VARCHAR}, #{staff,jdbcType=INTEGER}, ",
        "#{remark,jdbcType=VARCHAR})"
    })
    int insert(MaterialReceived record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_received
     *
     * @mbg.generated Sun Jan 28 21:12:17 CST 2018
     */
    @InsertProvider(type=MaterialReceivedSqlProvider.class, method="insertSelective")
    int insertSelective(MaterialReceived record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_received
     *
     * @mbg.generated Sun Jan 28 21:12:17 CST 2018
     */
    @SelectProvider(type=MaterialReceivedSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="project", property="project", jdbcType=JdbcType.INTEGER),
        @Result(column="node", property="node", jdbcType=JdbcType.VARCHAR),
        @Result(column="program", property="program", jdbcType=JdbcType.VARCHAR),
        @Result(column="iprocedure", property="iprocedure", jdbcType=JdbcType.VARCHAR),
        @Result(column="mechainc", property="mechainc", jdbcType=JdbcType.INTEGER),
        @Result(column="supplier", property="supplier", jdbcType=JdbcType.INTEGER),
        @Result(column="supplier_name", property="supplierName", jdbcType=JdbcType.VARCHAR),
        @Result(column="material", property="material", jdbcType=JdbcType.INTEGER),
        @Result(column="plate_number", property="plateNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="icount", property="icount", jdbcType=JdbcType.INTEGER),
        @Result(column="base_type", property="baseType", jdbcType=JdbcType.VARCHAR),
        @Result(column="material_spec", property="materialSpec", jdbcType=JdbcType.VARCHAR),
        @Result(column="distance", property="distance", jdbcType=JdbcType.INTEGER),
        @Result(column="material_price", property="materialPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="date", property="date", jdbcType=JdbcType.VARCHAR),
        @Result(column="unit_price", property="unitPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="material_name", property="materialName", jdbcType=JdbcType.VARCHAR),
        @Result(column="unit_freight_price", property="unitFreightPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="freight_price", property="freightPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="staff_name", property="staffName", jdbcType=JdbcType.VARCHAR),
        @Result(column="staff", property="staff", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<MaterialReceived> selectByExample(MaterialReceivedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_received
     *
     * @mbg.generated Sun Jan 28 21:12:17 CST 2018
     */
    @Select({
        "select",
        "id, project, node, program, iprocedure, mechainc, supplier, supplier_name, material, ",
        "plate_number, icount, base_type, material_spec, distance, material_price, create_date, ",
        "date, unit_price, material_name, unit_freight_price, freight_price, staff_name, ",
        "staff, remark",
        "from material_received",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="project", property="project", jdbcType=JdbcType.INTEGER),
        @Result(column="node", property="node", jdbcType=JdbcType.VARCHAR),
        @Result(column="program", property="program", jdbcType=JdbcType.VARCHAR),
        @Result(column="iprocedure", property="iprocedure", jdbcType=JdbcType.VARCHAR),
        @Result(column="mechainc", property="mechainc", jdbcType=JdbcType.INTEGER),
        @Result(column="supplier", property="supplier", jdbcType=JdbcType.INTEGER),
        @Result(column="supplier_name", property="supplierName", jdbcType=JdbcType.VARCHAR),
        @Result(column="material", property="material", jdbcType=JdbcType.INTEGER),
        @Result(column="plate_number", property="plateNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="icount", property="icount", jdbcType=JdbcType.INTEGER),
        @Result(column="base_type", property="baseType", jdbcType=JdbcType.VARCHAR),
        @Result(column="material_spec", property="materialSpec", jdbcType=JdbcType.VARCHAR),
        @Result(column="distance", property="distance", jdbcType=JdbcType.INTEGER),
        @Result(column="material_price", property="materialPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="date", property="date", jdbcType=JdbcType.VARCHAR),
        @Result(column="unit_price", property="unitPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="material_name", property="materialName", jdbcType=JdbcType.VARCHAR),
        @Result(column="unit_freight_price", property="unitFreightPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="freight_price", property="freightPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="staff_name", property="staffName", jdbcType=JdbcType.VARCHAR),
        @Result(column="staff", property="staff", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    MaterialReceived selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_received
     *
     * @mbg.generated Sun Jan 28 21:12:17 CST 2018
     */
    @UpdateProvider(type=MaterialReceivedSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MaterialReceived record, @Param("example") MaterialReceivedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_received
     *
     * @mbg.generated Sun Jan 28 21:12:17 CST 2018
     */
    @UpdateProvider(type=MaterialReceivedSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MaterialReceived record, @Param("example") MaterialReceivedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_received
     *
     * @mbg.generated Sun Jan 28 21:12:17 CST 2018
     */
    @UpdateProvider(type=MaterialReceivedSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MaterialReceived record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_received
     *
     * @mbg.generated Sun Jan 28 21:12:17 CST 2018
     */
    @Update({
        "update material_received",
        "set project = #{project,jdbcType=INTEGER},",
          "node = #{node,jdbcType=VARCHAR},",
          "program = #{program,jdbcType=VARCHAR},",
          "iprocedure = #{iprocedure,jdbcType=VARCHAR},",
          "mechainc = #{mechainc,jdbcType=INTEGER},",
          "supplier = #{supplier,jdbcType=INTEGER},",
          "supplier_name = #{supplierName,jdbcType=VARCHAR},",
          "material = #{material,jdbcType=INTEGER},",
          "plate_number = #{plateNumber,jdbcType=VARCHAR},",
          "icount = #{icount,jdbcType=INTEGER},",
          "base_type = #{baseType,jdbcType=VARCHAR},",
          "material_spec = #{materialSpec,jdbcType=VARCHAR},",
          "distance = #{distance,jdbcType=INTEGER},",
          "material_price = #{materialPrice,jdbcType=INTEGER},",
          "create_date = #{createDate,jdbcType=VARCHAR},",
          "date = #{date,jdbcType=VARCHAR},",
          "unit_price = #{unitPrice,jdbcType=INTEGER},",
          "material_name = #{materialName,jdbcType=VARCHAR},",
          "unit_freight_price = #{unitFreightPrice,jdbcType=INTEGER},",
          "freight_price = #{freightPrice,jdbcType=INTEGER},",
          "staff_name = #{staffName,jdbcType=VARCHAR},",
          "staff = #{staff,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MaterialReceived record);
	
    @SelectProvider(type=MaterialReceivedSqlProvider.class, method="selectAllGroup")
    @Results({
        @Result(column="materialName", property="materialName", jdbcType=JdbcType.VARCHAR),
        @Result(column="node", property="node", jdbcType=JdbcType.VARCHAR),
        @Result(column="program", property="program", jdbcType=JdbcType.VARCHAR),
        @Result(column="baseType", property="baseType", jdbcType=JdbcType.VARCHAR),
        @Result(column="icount", property="icount", jdbcType=JdbcType.INTEGER),
       
    })
    List<MaterialChartModel> selectAllGroup(@Param("project")int project);
    
    
    
    @SelectProvider(type=MaterialReceivedSqlProvider.class, method="selectAllGroupByDate")
    @Results({
         @Result(column="materialName", property="materialName", jdbcType=JdbcType.VARCHAR),
         @Result(column="node", property="node", jdbcType=JdbcType.VARCHAR),
         @Result(column="program", property="program", jdbcType=JdbcType.VARCHAR),
         @Result(column="baseType", property="baseType", jdbcType=JdbcType.VARCHAR),
         @Result(column="icount", property="icount", jdbcType=JdbcType.INTEGER),
    })
    List<MaterialChartModel> selectAllGroupByDate(@Param("project")int project,@Param("date")String date);
}