package com.core.mapper;

import com.core.entity.MechanicsPrice;
import com.core.entity.MechanicsPriceExample;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MechanicsPriceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mechanics_price
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@SelectProvider(type = MechanicsPriceSqlProvider.class, method = "countByExample")
	long countByExample(MechanicsPriceExample example);

	
	@SelectProvider(type = MechanicsPriceSqlProvider.class, method = "sumPriceByExample")
	long sumPriceByExample(MechanicsPriceExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mechanics_price
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@DeleteProvider(type = MechanicsPriceSqlProvider.class, method = "deleteByExample")
	int deleteByExample(MechanicsPriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mechanics_price
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@Delete({ "delete from mechanics_price", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mechanics_price
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@Insert({ "insert into mechanics_price (id, project, ", "program, node, iprocedure, ", "mechanic, mechanic_name, ",
			"driver_name, plate_number, ", "base_type, icount, ", "unit_price, unit_price_type, ",
			"date, create_date, ", "staff_name, staff, ", "price, remark)",
			"values (#{id,jdbcType=INTEGER}, #{project,jdbcType=INTEGER}, ",
			"#{program,jdbcType=VARCHAR}, #{node,jdbcType=VARCHAR}, #{iprocedure,jdbcType=VARCHAR}, ",
			"#{mechanic,jdbcType=INTEGER}, #{mechanicName,jdbcType=VARCHAR}, ",
			"#{driverName,jdbcType=VARCHAR}, #{plateNumber,jdbcType=VARCHAR}, ",
			"#{baseType,jdbcType=VARCHAR}, #{icount,jdbcType=INTEGER}, ",
			"#{unitPrice,jdbcType=INTEGER}, #{unitPriceType,jdbcType=VARCHAR}, ",
			"#{date,jdbcType=VARCHAR}, #{createDate,jdbcType=VARCHAR}, ",
			"#{staffName,jdbcType=VARCHAR}, #{staff,jdbcType=INTEGER}, ",
			"#{price,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR})" })
	int insert(MechanicsPrice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mechanics_price
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@InsertProvider(type = MechanicsPriceSqlProvider.class, method = "insertSelective")
	int insertSelective(MechanicsPrice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mechanics_price
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@SelectProvider(type = MechanicsPriceSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "project", property = "project", jdbcType = JdbcType.INTEGER),
			@Result(column = "program", property = "program", jdbcType = JdbcType.VARCHAR),
			@Result(column = "node", property = "node", jdbcType = JdbcType.VARCHAR),
			@Result(column = "iprocedure", property = "iprocedure", jdbcType = JdbcType.VARCHAR),
			@Result(column = "mechanic", property = "mechanic", jdbcType = JdbcType.INTEGER),
			@Result(column = "mechanic_name", property = "mechanicName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "driver_name", property = "driverName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "plate_number", property = "plateNumber", jdbcType = JdbcType.VARCHAR),
			@Result(column = "base_type", property = "baseType", jdbcType = JdbcType.VARCHAR),
			@Result(column = "icount", property = "icount", jdbcType = JdbcType.INTEGER),
			@Result(column = "unit_price", property = "unitPrice", jdbcType = JdbcType.INTEGER),
			@Result(column = "unit_price_type", property = "unitPriceType", jdbcType = JdbcType.VARCHAR),
			@Result(column = "date", property = "date", jdbcType = JdbcType.VARCHAR),
			@Result(column = "create_date", property = "createDate", jdbcType = JdbcType.VARCHAR),
			@Result(column = "staff_name", property = "staffName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "staff", property = "staff", jdbcType = JdbcType.INTEGER),
			@Result(column = "price", property = "price", jdbcType = JdbcType.INTEGER),
			@Result(column = "remark", property = "remark", jdbcType = JdbcType.VARCHAR) })
	List<MechanicsPrice> selectByExample(MechanicsPriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mechanics_price
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@Select({ "select", "id, project, program, node, iprocedure, mechanic, mechanic_name, driver_name, ",
			"plate_number, base_type, icount, unit_price, unit_price_type, date, create_date, ",
			"staff_name, staff, price, remark", "from mechanics_price", "where id = #{id,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "project", property = "project", jdbcType = JdbcType.INTEGER),
			@Result(column = "program", property = "program", jdbcType = JdbcType.VARCHAR),
			@Result(column = "node", property = "node", jdbcType = JdbcType.VARCHAR),
			@Result(column = "iprocedure", property = "iprocedure", jdbcType = JdbcType.VARCHAR),
			@Result(column = "mechanic", property = "mechanic", jdbcType = JdbcType.INTEGER),
			@Result(column = "mechanic_name", property = "mechanicName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "driver_name", property = "driverName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "plate_number", property = "plateNumber", jdbcType = JdbcType.VARCHAR),
			@Result(column = "base_type", property = "baseType", jdbcType = JdbcType.VARCHAR),
			@Result(column = "icount", property = "icount", jdbcType = JdbcType.INTEGER),
			@Result(column = "unit_price", property = "unitPrice", jdbcType = JdbcType.INTEGER),
			@Result(column = "unit_price_type", property = "unitPriceType", jdbcType = JdbcType.VARCHAR),
			@Result(column = "date", property = "date", jdbcType = JdbcType.VARCHAR),
			@Result(column = "create_date", property = "createDate", jdbcType = JdbcType.VARCHAR),
			@Result(column = "staff_name", property = "staffName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "staff", property = "staff", jdbcType = JdbcType.INTEGER),
			@Result(column = "price", property = "price", jdbcType = JdbcType.INTEGER),
			@Result(column = "remark", property = "remark", jdbcType = JdbcType.VARCHAR) })
	MechanicsPrice selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mechanics_price
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@UpdateProvider(type = MechanicsPriceSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") MechanicsPrice record,
			@Param("example") MechanicsPriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mechanics_price
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@UpdateProvider(type = MechanicsPriceSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") MechanicsPrice record, @Param("example") MechanicsPriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mechanics_price
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@UpdateProvider(type = MechanicsPriceSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(MechanicsPrice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mechanics_price
	 * @mbg.generated  Thu Jan 25 10:11:12 CST 2018
	 */
	@Update({ "update mechanics_price", "set project = #{project,jdbcType=INTEGER},",
			"program = #{program,jdbcType=VARCHAR},", "node = #{node,jdbcType=VARCHAR},",
			"iprocedure = #{iprocedure,jdbcType=VARCHAR},", "mechanic = #{mechanic,jdbcType=INTEGER},",
			"mechanic_name = #{mechanicName,jdbcType=VARCHAR},", "driver_name = #{driverName,jdbcType=VARCHAR},",
			"plate_number = #{plateNumber,jdbcType=VARCHAR},", "base_type = #{baseType,jdbcType=VARCHAR},",
			"icount = #{icount,jdbcType=INTEGER},", "unit_price = #{unitPrice,jdbcType=INTEGER},",
			"unit_price_type = #{unitPriceType,jdbcType=VARCHAR},", "date = #{date,jdbcType=VARCHAR},",
			"create_date = #{createDate,jdbcType=VARCHAR},", "staff_name = #{staffName,jdbcType=VARCHAR},",
			"staff = #{staff,jdbcType=INTEGER},", "price = #{price,jdbcType=INTEGER},",
			"remark = #{remark,jdbcType=VARCHAR}", "where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(MechanicsPrice record);
	

}