package com.core.mapper;

import com.core.entity.Mechanics;
import com.core.entity.MechanicsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MechanicsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    @SelectProvider(type=MechanicsSqlProvider.class, method="countByExample")
    long countByExample(MechanicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    @DeleteProvider(type=MechanicsSqlProvider.class, method="deleteByExample")
    int deleteByExample(MechanicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    @Delete({
        "delete from mechanics",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    @Insert({
        "insert into mechanics (id, m_name, ",
        "code, plate_number, ",
        "model, capacity, ",
        "driver_idcard, driver_name, ",
        "driver_mobile, create_date, ",
        "m_type, update_date, ",
        "remark)",
        "values (#{id,jdbcType=INTEGER}, #{mName,jdbcType=VARCHAR}, ",
        "#{code,jdbcType=VARCHAR}, #{plateNumber,jdbcType=VARCHAR}, ",
        "#{model,jdbcType=VARCHAR}, #{capacity,jdbcType=VARCHAR}, ",
        "#{driverIdcard,jdbcType=VARCHAR}, #{driverName,jdbcType=VARCHAR}, ",
        "#{driverMobile,jdbcType=VARCHAR}, #{createDate,jdbcType=VARCHAR}, ",
        "#{mType,jdbcType=INTEGER}, #{updateDate,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR})"
    })
    int insert(Mechanics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    @Options(useGeneratedKeys=true)
    @InsertProvider(type=MechanicsSqlProvider.class, method="insertSelective")
    int insertSelective(Mechanics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    @SelectProvider(type=MechanicsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="m_name", property="mName", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="plate_number", property="plateNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="model", property="model", jdbcType=JdbcType.VARCHAR),
        @Result(column="capacity", property="capacity", jdbcType=JdbcType.VARCHAR),
        @Result(column="driver_idcard", property="driverIdcard", jdbcType=JdbcType.VARCHAR),
        @Result(column="driver_name", property="driverName", jdbcType=JdbcType.VARCHAR),
        @Result(column="driver_mobile", property="driverMobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="m_type", property="mType", jdbcType=JdbcType.INTEGER),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<Mechanics> selectByExample(MechanicsExample example);
    
    
    @SelectProvider(type=MechanicsSqlProvider.class, method="selectMechaincs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="m_name", property="mName", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="plate_number", property="plateNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="model", property="model", jdbcType=JdbcType.VARCHAR),
        @Result(column="capacity", property="capacity", jdbcType=JdbcType.VARCHAR),
        @Result(column="driver_idcard", property="driverIdcard", jdbcType=JdbcType.VARCHAR),
        @Result(column="driver_name", property="driverName", jdbcType=JdbcType.VARCHAR),
        @Result(column="driver_mobile", property="driverMobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="m_type", property="mType", jdbcType=JdbcType.INTEGER),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<Mechanics> selectMechaincs(@Param("project")int project);
    
    
    
    @SelectProvider(type=MechanicsSqlProvider.class, method="selectSkips")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="m_name", property="mName", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="plate_number", property="plateNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="model", property="model", jdbcType=JdbcType.VARCHAR),
        @Result(column="capacity", property="capacity", jdbcType=JdbcType.VARCHAR),
        @Result(column="driver_idcard", property="driverIdcard", jdbcType=JdbcType.VARCHAR),
        @Result(column="driver_name", property="driverName", jdbcType=JdbcType.VARCHAR),
        @Result(column="driver_mobile", property="driverMobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="m_type", property="mType", jdbcType=JdbcType.INTEGER),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<Mechanics> selectSkips(@Param("project")int project);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    @Select({
        "select",
        "id, m_name, code, plate_number, model, capacity, driver_idcard, driver_name, ",
        "driver_mobile, create_date, m_type, update_date, remark",
        "from mechanics",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="m_name", property="mName", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="plate_number", property="plateNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="model", property="model", jdbcType=JdbcType.VARCHAR),
        @Result(column="capacity", property="capacity", jdbcType=JdbcType.VARCHAR),
        @Result(column="driver_idcard", property="driverIdcard", jdbcType=JdbcType.VARCHAR),
        @Result(column="driver_name", property="driverName", jdbcType=JdbcType.VARCHAR),
        @Result(column="driver_mobile", property="driverMobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="m_type", property="mType", jdbcType=JdbcType.INTEGER),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    Mechanics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    @UpdateProvider(type=MechanicsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Mechanics record, @Param("example") MechanicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    @UpdateProvider(type=MechanicsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Mechanics record, @Param("example") MechanicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    @UpdateProvider(type=MechanicsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Mechanics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    @Update({
        "update mechanics",
        "set m_name = #{mName,jdbcType=VARCHAR},",
          "code = #{code,jdbcType=VARCHAR},",
          "plate_number = #{plateNumber,jdbcType=VARCHAR},",
          "model = #{model,jdbcType=VARCHAR},",
          "capacity = #{capacity,jdbcType=VARCHAR},",
          "driver_idcard = #{driverIdcard,jdbcType=VARCHAR},",
          "driver_name = #{driverName,jdbcType=VARCHAR},",
          "driver_mobile = #{driverMobile,jdbcType=VARCHAR},",
          "create_date = #{createDate,jdbcType=VARCHAR},",
          "m_type = #{mType,jdbcType=INTEGER},",
          "update_date = #{updateDate,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Mechanics record);
}