package com.core.mapper;

import com.core.entity.MechanicsProjectOwner;
import com.core.entity.MechanicsProjectOwnerExample.Criteria;
import com.core.entity.MechanicsProjectOwnerExample.Criterion;
import com.core.util.Utils;
import com.core.entity.MechanicsProjectOwnerExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class MechanicsProjectOwnerSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics_project_owner
     *
     * @mbg.generated Thu Dec 21 16:06:03 CST 2017
     */
    public String countByExample(MechanicsProjectOwnerExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("mechanics_project_owner");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics_project_owner
     *
     * @mbg.generated Thu Dec 21 16:06:03 CST 2017
     */
    public String deleteByExample(MechanicsProjectOwnerExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM(Utils.getDatabase()+".mechanics_project_owner");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics_project_owner
     *
     * @mbg.generated Thu Dec 21 16:06:03 CST 2017
     */
    public String insertSelective(MechanicsProjectOwner record) {
        SQL sql = new SQL();
        sql.INSERT_INTO(Utils.getDatabase()+".mechanics_project_owner");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getProject() != null) {
            sql.VALUES("project", "#{project,jdbcType=INTEGER}");
        }
        
        if (record.getMechanics() != null) {
            sql.VALUES("mechanics", "#{mechanics,jdbcType=INTEGER}");
        }
        
        if (record.getUnitPrice() != null) {
            sql.VALUES("unit_price", "#{unitPrice,jdbcType=INTEGER}");
        }
        
        if (record.getType() != null) {
            sql.VALUES("type", "#{type,jdbcType=INTEGER}");
        }
        
        if (record.getOwner() != null) {
            sql.VALUES("owner", "#{owner,jdbcType=INTEGER}");
        }
        
        if (record.getUnitPriceType() != null) {
            sql.VALUES("unit_price_type", "#{unitPriceType,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics_project_owner
     *
     * @mbg.generated Thu Dec 21 16:06:03 CST 2017
     */
    public String selectByExample(MechanicsProjectOwnerExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("project");
        sql.SELECT("mechanics");
        sql.SELECT("unit_price");
        sql.SELECT("type");
        sql.SELECT("owner");
        sql.SELECT("unit_price_type");
        sql.FROM(Utils.getDatabase()+".mechanics_project_owner");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        if(example.isDistinct()) {
        	return sql.toString()+" group by mechanics";
        }
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics_project_owner
     *
     * @mbg.generated Thu Dec 21 16:06:03 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        MechanicsProjectOwner record = (MechanicsProjectOwner) parameter.get("record");
        MechanicsProjectOwnerExample example = (MechanicsProjectOwnerExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE(Utils.getDatabase()+".mechanics_project_owner");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getProject() != null) {
            sql.SET("project = #{record.project,jdbcType=INTEGER}");
        }
        
        if (record.getMechanics() != null) {
            sql.SET("mechanics = #{record.mechanics,jdbcType=INTEGER}");
        }
        
        if (record.getUnitPrice() != null) {
            sql.SET("unit_price = #{record.unitPrice,jdbcType=INTEGER}");
        }
        
        if (record.getType() != null) {
            sql.SET("type = #{record.type,jdbcType=INTEGER}");
        }
        
        if (record.getOwner() != null) {
            sql.SET("owner = #{record.owner,jdbcType=INTEGER}");
        }
        
        if (record.getUnitPriceType() != null) {
            sql.SET("unit_price_type = #{record.unitPriceType,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics_project_owner
     *
     * @mbg.generated Thu Dec 21 16:06:03 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE(Utils.getDatabase()+".mechanics_project_owner");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("project = #{record.project,jdbcType=INTEGER}");
        sql.SET("mechanics = #{record.mechanics,jdbcType=INTEGER}");
        sql.SET("unit_price = #{record.unitPrice,jdbcType=INTEGER}");
        sql.SET("type = #{record.type,jdbcType=INTEGER}");
        sql.SET("owner = #{record.owner,jdbcType=INTEGER}");
        sql.SET("unit_price_type = #{record.unitPriceType,jdbcType=INTEGER}");
        
        MechanicsProjectOwnerExample example = (MechanicsProjectOwnerExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics_project_owner
     *
     * @mbg.generated Thu Dec 21 16:06:03 CST 2017
     */
    public String updateByPrimaryKeySelective(MechanicsProjectOwner record) {
        SQL sql = new SQL();
        sql.UPDATE("mechanics_project_owner");
        
        if (record.getProject() != null) {
            sql.SET("project = #{project,jdbcType=INTEGER}");
        }
        
        if (record.getMechanics() != null) {
            sql.SET("mechanics = #{mechanics,jdbcType=INTEGER}");
        }
        
        if (record.getUnitPrice() != null) {
            sql.SET("unit_price = #{unitPrice,jdbcType=INTEGER}");
        }
        
        if (record.getType() != null) {
            sql.SET("type = #{type,jdbcType=INTEGER}");
        }
        
        if (record.getOwner() != null) {
            sql.SET("owner = #{owner,jdbcType=INTEGER}");
        }
        
        if (record.getUnitPriceType() != null) {
            sql.SET("unit_price_type = #{unitPriceType,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics_project_owner
     *
     * @mbg.generated Thu Dec 21 16:06:03 CST 2017
     */
    protected void applyWhere(SQL sql, MechanicsProjectOwnerExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}