package com.core.mapper;

import com.core.entity.Mechanics;
import com.core.entity.MechanicsExample.Criteria;
import com.core.entity.MechanicsExample.Criterion;
import com.core.util.Utils;
import com.core.entity.MechanicsExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.jdbc.SQL;

public class MechanicsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    public String countByExample(MechanicsExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM(Utils.getDatabase()+".mechanics");
        applyWhere(sql, example, false);
        return sql.toString();
    }
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    public String deleteByExample(MechanicsExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM(Utils.getDatabase()+".mechanics");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    public String insertSelective(Mechanics record) {
        SQL sql = new SQL();
        sql.INSERT_INTO(Utils.getDatabase()+".mechanics");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getmName() != null) {
            sql.VALUES("m_name", "#{mName,jdbcType=VARCHAR}");
        }
        
        if (record.getCode() != null) {
            sql.VALUES("code", "#{code,jdbcType=VARCHAR}");
        }
        
        if (record.getPlateNumber() != null) {
            sql.VALUES("plate_number", "#{plateNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getModel() != null) {
            sql.VALUES("model", "#{model,jdbcType=VARCHAR}");
        }
        
        if (record.getCapacity() != null) {
            sql.VALUES("capacity", "#{capacity,jdbcType=VARCHAR}");
        }
        
        if (record.getDriverIdcard() != null) {
            sql.VALUES("driver_idcard", "#{driverIdcard,jdbcType=VARCHAR}");
        }
        
        if (record.getDriverName() != null) {
            sql.VALUES("driver_name", "#{driverName,jdbcType=VARCHAR}");
        }
        
        if (record.getDriverMobile() != null) {
            sql.VALUES("driver_mobile", "#{driverMobile,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            sql.VALUES("create_date", "#{createDate,jdbcType=VARCHAR}");
        }
        
        if (record.getmType() != null) {
            sql.VALUES("m_type", "#{mType,jdbcType=INTEGER}");
        }
        
        if (record.getUpdateDate() != null) {
            sql.VALUES("update_date", "#{updateDate,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }
    //SELECT m.* FROM `mechanics_project_owner`  mpo, `mechanics` m WHERE mpo.`project` = 35 AND mpo.`owner`!='' AND mpo.`mechanics` AND m.`id` = mpo.`mechanics`
    public String selectMechaincs(@Param("project")int project) {
        String sql ="SELECT m.* FROM `"+Utils.getDatabase()+"`.`mechanics_project_owner`  mpo,`"+Utils.getDatabase()+"`.`mechanics` m WHERE mpo.`project` = "+project+" AND mpo.`owner`!='' AND m.`id` = mpo.`mechanics` AND m.`m_type`= 1 GROUP BY m.`id` ";
        return sql;
    }
    
    public String selectSkips(@Param("project")int project) {
        String sql ="SELECT m.* FROM `"+Utils.getDatabase()+"`.`skip_material_price`  smp,`"+Utils.getDatabase()+"`.`mechanics` m WHERE smp.`project` = "+project+" AND smp.`foreman`!='' AND m.`id` = smp.`mechainc`AND m.`m_type`= 2 GROUP BY m.`id`";
        return sql;
    }
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    public String selectByExample(MechanicsExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("m_name");
        sql.SELECT("code");
        sql.SELECT("plate_number");
        sql.SELECT("model");
        sql.SELECT("capacity");
        sql.SELECT("driver_idcard");
        sql.SELECT("driver_name");
        sql.SELECT("driver_mobile");
        sql.SELECT("create_date");
        sql.SELECT("m_type");
        sql.SELECT("update_date");
        sql.SELECT("remark");
        sql.FROM(Utils.getDatabase()+".mechanics");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Mechanics record = (Mechanics) parameter.get("record");
        MechanicsExample example = (MechanicsExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE(Utils.getDatabase()+".mechanics");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getmName() != null) {
            sql.SET("m_name = #{record.mName,jdbcType=VARCHAR}");
        }
        
        if (record.getCode() != null) {
            sql.SET("code = #{record.code,jdbcType=VARCHAR}");
        }
        
        if (record.getPlateNumber() != null) {
            sql.SET("plate_number = #{record.plateNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getModel() != null) {
            sql.SET("model = #{record.model,jdbcType=VARCHAR}");
        }
        
        if (record.getCapacity() != null) {
            sql.SET("capacity = #{record.capacity,jdbcType=VARCHAR}");
        }
        
        if (record.getDriverIdcard() != null) {
            sql.SET("driver_idcard = #{record.driverIdcard,jdbcType=VARCHAR}");
        }
        
        if (record.getDriverName() != null) {
            sql.SET("driver_name = #{record.driverName,jdbcType=VARCHAR}");
        }
        
        if (record.getDriverMobile() != null) {
            sql.SET("driver_mobile = #{record.driverMobile,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            sql.SET("create_date = #{record.createDate,jdbcType=VARCHAR}");
        }
        
        if (record.getmType() != null) {
            sql.SET("m_type = #{record.mType,jdbcType=INTEGER}");
        }
        
        if (record.getUpdateDate() != null) {
            sql.SET("update_date = #{record.updateDate,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE(Utils.getDatabase()+".mechanics");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("m_name = #{record.mName,jdbcType=VARCHAR}");
        sql.SET("code = #{record.code,jdbcType=VARCHAR}");
        sql.SET("plate_number = #{record.plateNumber,jdbcType=VARCHAR}");
        sql.SET("model = #{record.model,jdbcType=VARCHAR}");
        sql.SET("capacity = #{record.capacity,jdbcType=VARCHAR}");
        sql.SET("driver_idcard = #{record.driverIdcard,jdbcType=VARCHAR}");
        sql.SET("driver_name = #{record.driverName,jdbcType=VARCHAR}");
        sql.SET("driver_mobile = #{record.driverMobile,jdbcType=VARCHAR}");
        sql.SET("create_date = #{record.createDate,jdbcType=VARCHAR}");
        sql.SET("m_type = #{record.mType,jdbcType=INTEGER}");
        sql.SET("update_date = #{record.updateDate,jdbcType=VARCHAR}");
        sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
        
        MechanicsExample example = (MechanicsExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    public String updateByPrimaryKeySelective(Mechanics record) {
        SQL sql = new SQL();
        sql.UPDATE(Utils.getDatabase()+".mechanics");
        
        if (record.getmName() != null) {
            sql.SET("m_name = #{mName,jdbcType=VARCHAR}");
        }
        
        if (record.getCode() != null) {
            sql.SET("code = #{code,jdbcType=VARCHAR}");
        }
        
        if (record.getPlateNumber() != null) {
            sql.SET("plate_number = #{plateNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getModel() != null) {
            sql.SET("model = #{model,jdbcType=VARCHAR}");
        }
        
        if (record.getCapacity() != null) {
            sql.SET("capacity = #{capacity,jdbcType=VARCHAR}");
        }
        
        if (record.getDriverIdcard() != null) {
            sql.SET("driver_idcard = #{driverIdcard,jdbcType=VARCHAR}");
        }
        
        if (record.getDriverName() != null) {
            sql.SET("driver_name = #{driverName,jdbcType=VARCHAR}");
        }
        
        if (record.getDriverMobile() != null) {
            sql.SET("driver_mobile = #{driverMobile,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            sql.SET("create_date = #{createDate,jdbcType=VARCHAR}");
        }
        
        if (record.getmType() != null) {
            sql.SET("m_type = #{mType,jdbcType=INTEGER}");
        }
        
        if (record.getUpdateDate() != null) {
            sql.SET("update_date = #{updateDate,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanics
     *
     * @mbg.generated Fri Dec 22 10:16:56 CST 2017
     */
    protected void applyWhere(SQL sql, MechanicsExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}