package com.core.mapper;

import com.core.entity.PersonAccount;
import com.core.entity.PersonAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PersonAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_account
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @SelectProvider(type=PersonAccountSqlProvider.class, method="countByExample")
    long countByExample(PersonAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_account
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @DeleteProvider(type=PersonAccountSqlProvider.class, method="deleteByExample")
    int deleteByExample(PersonAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_account
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @Delete({
        "delete from person_account",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_account
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @Insert({
        "insert into person_account (id, user, ",
        "type, loan, income, ",
        "date, remark)",
        "values (#{id,jdbcType=INTEGER}, #{user,jdbcType=INTEGER}, ",
        "#{type,jdbcType=INTEGER}, #{loan,jdbcType=INTEGER}, #{income,jdbcType=INTEGER}, ",
        "#{date,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(PersonAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_account
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @InsertProvider(type=PersonAccountSqlProvider.class, method="insertSelective")
    int insertSelective(PersonAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_account
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @SelectProvider(type=PersonAccountSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user", property="user", jdbcType=JdbcType.INTEGER),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="loan", property="loan", jdbcType=JdbcType.INTEGER),
        @Result(column="income", property="income", jdbcType=JdbcType.INTEGER),
        @Result(column="date", property="date", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<PersonAccount> selectByExample(PersonAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_account
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @Select({
        "select",
        "id, user, type, loan, income, date, remark",
        "from person_account",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user", property="user", jdbcType=JdbcType.INTEGER),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="loan", property="loan", jdbcType=JdbcType.INTEGER),
        @Result(column="income", property="income", jdbcType=JdbcType.INTEGER),
        @Result(column="date", property="date", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    PersonAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_account
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @UpdateProvider(type=PersonAccountSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PersonAccount record, @Param("example") PersonAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_account
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @UpdateProvider(type=PersonAccountSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PersonAccount record, @Param("example") PersonAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_account
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @UpdateProvider(type=PersonAccountSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PersonAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_account
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @Update({
        "update person_account",
        "set user = #{user,jdbcType=INTEGER},",
          "type = #{type,jdbcType=INTEGER},",
          "loan = #{loan,jdbcType=INTEGER},",
          "income = #{income,jdbcType=INTEGER},",
          "date = #{date,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PersonAccount record);
}