package com.core.mapper;

import com.core.entity.PriceFluctuation;
import com.core.entity.PriceFluctuationExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PriceFluctuationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_fluctuation
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @SelectProvider(type=PriceFluctuationSqlProvider.class, method="countByExample")
    long countByExample(PriceFluctuationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_fluctuation
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @DeleteProvider(type=PriceFluctuationSqlProvider.class, method="deleteByExample")
    int deleteByExample(PriceFluctuationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_fluctuation
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @Delete({
        "delete from price_fluctuation",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_fluctuation
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @Options(useGeneratedKeys=true)
    @Insert({
        "insert into price_fluctuation (id, price, ",
        "start_date, create_date, ",
        "type, remark)",
        "values (#{id,jdbcType=INTEGER}, #{price,jdbcType=INTEGER}, ",
        "#{startDate,jdbcType=VARCHAR}, #{createDate,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(PriceFluctuation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_fluctuation
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @Options(useGeneratedKeys=true)
    @InsertProvider(type=PriceFluctuationSqlProvider.class, method="insertSelective")
    int insertSelective(PriceFluctuation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_fluctuation
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @SelectProvider(type=PriceFluctuationSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="price", property="price", jdbcType=JdbcType.INTEGER),
        @Result(column="start_date", property="startDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<PriceFluctuation> selectByExample(PriceFluctuationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_fluctuation
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @Select({
        "select",
        "id, price, start_date, create_date, type, remark",
        "from ${database}.price_fluctuation",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="price", property="price", jdbcType=JdbcType.INTEGER),
        @Result(column="start_date", property="startDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    PriceFluctuation selectByPrimaryKey(@Param("database") String database,@Param("id")Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_fluctuation
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @UpdateProvider(type=PriceFluctuationSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PriceFluctuation record, @Param("example") PriceFluctuationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_fluctuation
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @UpdateProvider(type=PriceFluctuationSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PriceFluctuation record, @Param("example") PriceFluctuationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_fluctuation
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @UpdateProvider(type=PriceFluctuationSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PriceFluctuation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_fluctuation
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @Update({
        "update price_fluctuation",
        "set price = #{price,jdbcType=INTEGER},",
          "start_date = #{startDate,jdbcType=VARCHAR},",
          "create_date = #{createDate,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PriceFluctuation record);
}