package com.core.mapper;

import com.core.entity.ProjectForeman;
import com.core.entity.ProjectForemanExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ProjectForemanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_foreman
     *
     * @mbg.generated Thu Dec 14 18:51:20 CST 2017
     */
    @SelectProvider(type=ProjectForemanSqlProvider.class, method="countByExample")
    long countByExample(ProjectForemanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_foreman
     *
     * @mbg.generated Thu Dec 14 18:51:20 CST 2017
     */
    @DeleteProvider(type=ProjectForemanSqlProvider.class, method="deleteByExample")
    int deleteByExample(ProjectForemanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_foreman
     *
     * @mbg.generated Thu Dec 14 18:51:20 CST 2017
     */
    @Delete({
        "delete from project_foreman",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_foreman
     *
     * @mbg.generated Thu Dec 14 18:51:20 CST 2017
     */
    @Insert({
        "insert into project_foreman (id, foreman, ",
        "project)",
        "values (#{id,jdbcType=INTEGER}, #{foreman,jdbcType=INTEGER}, ",
        "#{project,jdbcType=INTEGER})"
    })
    int insert(ProjectForeman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_foreman
     *
     * @mbg.generated Thu Dec 14 18:51:20 CST 2017
     */
    @InsertProvider(type=ProjectForemanSqlProvider.class, method="insertSelective")
    int insertSelective(ProjectForeman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_foreman
     *
     * @mbg.generated Thu Dec 14 18:51:20 CST 2017
     */
    @SelectProvider(type=ProjectForemanSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="foreman", property="foreman", jdbcType=JdbcType.INTEGER),
        @Result(column="project", property="project", jdbcType=JdbcType.INTEGER)
    })
    List<ProjectForeman> selectByExample(ProjectForemanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_foreman
     *
     * @mbg.generated Thu Dec 14 18:51:20 CST 2017
     */
    @Select({
        "select",
        "id, foreman, project",
        "from project_foreman",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="foreman", property="foreman", jdbcType=JdbcType.INTEGER),
        @Result(column="project", property="project", jdbcType=JdbcType.INTEGER)
    })
    ProjectForeman selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_foreman
     *
     * @mbg.generated Thu Dec 14 18:51:20 CST 2017
     */
    @UpdateProvider(type=ProjectForemanSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ProjectForeman record, @Param("example") ProjectForemanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_foreman
     *
     * @mbg.generated Thu Dec 14 18:51:20 CST 2017
     */
    @UpdateProvider(type=ProjectForemanSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ProjectForeman record, @Param("example") ProjectForemanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_foreman
     *
     * @mbg.generated Thu Dec 14 18:51:20 CST 2017
     */
    @UpdateProvider(type=ProjectForemanSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ProjectForeman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_foreman
     *
     * @mbg.generated Thu Dec 14 18:51:20 CST 2017
     */
    @Update({
        "update project_foreman",
        "set foreman = #{foreman,jdbcType=INTEGER},",
          "project = #{project,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ProjectForeman record);
}