package com.core.mapper;

import com.core.entity.ProjectStaffPrice;
import com.core.entity.ProjectStaffPriceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ProjectStaffPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_staff_price
     *
     * @mbg.generated Thu Dec 14 19:02:09 CST 2017
     */
    @SelectProvider(type=ProjectStaffPriceSqlProvider.class, method="countByExample")
    long countByExample(ProjectStaffPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_staff_price
     *
     * @mbg.generated Thu Dec 14 19:02:09 CST 2017
     */
    @DeleteProvider(type=ProjectStaffPriceSqlProvider.class, method="deleteByExample")
    int deleteByExample(ProjectStaffPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_staff_price
     *
     * @mbg.generated Thu Dec 14 19:02:09 CST 2017
     */
    @Delete({
        "delete from project_staff_price",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_staff_price
     *
     * @mbg.generated Thu Dec 14 19:02:09 CST 2017
     */
    @Insert({
        "insert into project_staff_price (id, staff, ",
        "project, unit_price, ",
        "unit_price_type)",
        "values (#{id,jdbcType=INTEGER}, #{staff,jdbcType=INTEGER}, ",
        "#{project,jdbcType=INTEGER}, #{unitPrice,jdbcType=INTEGER}, ",
        "#{unitPriceType,jdbcType=INTEGER})"
    })
    int insert(ProjectStaffPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_staff_price
     *
     * @mbg.generated Thu Dec 14 19:02:09 CST 2017
     */
    @InsertProvider(type=ProjectStaffPriceSqlProvider.class, method="insertSelective")
    int insertSelective(ProjectStaffPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_staff_price
     *
     * @mbg.generated Thu Dec 14 19:02:09 CST 2017
     */
    @SelectProvider(type=ProjectStaffPriceSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="staff", property="staff", jdbcType=JdbcType.INTEGER),
        @Result(column="project", property="project", jdbcType=JdbcType.INTEGER),
        @Result(column="unit_price", property="unitPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="unit_price_type", property="unitPriceType", jdbcType=JdbcType.INTEGER)
    })
    List<ProjectStaffPrice> selectByExample(ProjectStaffPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_staff_price
     *
     * @mbg.generated Thu Dec 14 19:02:09 CST 2017
     */
    @Select({
        "select",
        "id, staff, project, unit_price, unit_price_type",
        "from project_staff_price",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="staff", property="staff", jdbcType=JdbcType.INTEGER),
        @Result(column="project", property="project", jdbcType=JdbcType.INTEGER),
        @Result(column="unit_price", property="unitPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="unit_price_type", property="unitPriceType", jdbcType=JdbcType.INTEGER)
    })
    ProjectStaffPrice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_staff_price
     *
     * @mbg.generated Thu Dec 14 19:02:09 CST 2017
     */
    @UpdateProvider(type=ProjectStaffPriceSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ProjectStaffPrice record, @Param("example") ProjectStaffPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_staff_price
     *
     * @mbg.generated Thu Dec 14 19:02:09 CST 2017
     */
    @UpdateProvider(type=ProjectStaffPriceSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ProjectStaffPrice record, @Param("example") ProjectStaffPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_staff_price
     *
     * @mbg.generated Thu Dec 14 19:02:09 CST 2017
     */
    @UpdateProvider(type=ProjectStaffPriceSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ProjectStaffPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_staff_price
     *
     * @mbg.generated Thu Dec 14 19:02:09 CST 2017
     */
    @Update({
        "update project_staff_price",
        "set staff = #{staff,jdbcType=INTEGER},",
          "project = #{project,jdbcType=INTEGER},",
          "unit_price = #{unitPrice,jdbcType=INTEGER},",
          "unit_price_type = #{unitPriceType,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ProjectStaffPrice record);
}