package com.core.mapper;

import com.core.entity.RoleMenu;
import com.core.entity.RoleMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface RoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @SelectProvider(type=RoleMenuSqlProvider.class, method="countByExample")
    long countByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @DeleteProvider(type=RoleMenuSqlProvider.class, method="deleteByExample")
    int deleteByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @Delete({
        "delete from role_menu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @Insert({
        "insert into role_menu (id, role, ",
        "menu, order_num)",
        "values (#{id,jdbcType=INTEGER}, #{role,jdbcType=INTEGER}, ",
        "#{menu,jdbcType=INTEGER}, #{orderNum,jdbcType=INTEGER})"
    })
    int insert(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @InsertProvider(type=RoleMenuSqlProvider.class, method="insertSelective")
    int insertSelective(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @SelectProvider(type=RoleMenuSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="role", property="role", jdbcType=JdbcType.INTEGER),
        @Result(column="menu", property="menu", jdbcType=JdbcType.INTEGER),
        @Result(column="order_num", property="orderNum", jdbcType=JdbcType.INTEGER)
    })
    List<RoleMenu> selectByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @Select({
        "select",
        "id, role, menu, order_num",
        "from role_menu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="role", property="role", jdbcType=JdbcType.INTEGER),
        @Result(column="menu", property="menu", jdbcType=JdbcType.INTEGER),
        @Result(column="order_num", property="orderNum", jdbcType=JdbcType.INTEGER)
    })
    RoleMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @UpdateProvider(type=RoleMenuSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") RoleMenu record, @Param("example") RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @UpdateProvider(type=RoleMenuSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") RoleMenu record, @Param("example") RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @UpdateProvider(type=RoleMenuSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Wed Dec 13 15:29:38 CST 2017
     */
    @Update({
        "update role_menu",
        "set role = #{role,jdbcType=INTEGER},",
          "menu = #{menu,jdbcType=INTEGER},",
          "order_num = #{orderNum,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(RoleMenu record);
}