package com.core.mapper;

import com.core.entity.SkipMaterialPrice;
import com.core.entity.SkipMaterialPriceExample;
import com.core.entity.SkipMaterialPriceKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SkipMaterialPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
	 @SelectProvider(type=SkipMaterialPriceSqlProvider.class, method="countByExample")
	long countByExample(SkipMaterialPrice sp,SkipMaterialPriceExample example);
	 
	 
    @SelectProvider(type=SkipMaterialPriceSqlProvider.class, method="selectByExampleGroupBySkip")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="project", property="project", jdbcType=JdbcType.INTEGER),
        @Result(column="foreman", property="foreman", jdbcType=JdbcType.INTEGER),
        @Result(column="mechainc", property="mechainc", jdbcType=JdbcType.INTEGER),
        @Result(column="material_type", property="materialType", jdbcType=JdbcType.INTEGER),
        @Result(column="base_price_type", property="basePriceType", jdbcType=JdbcType.INTEGER),
        @Result(column="unit_price", property="unitPrice", jdbcType=JdbcType.INTEGER),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<SkipMaterialPrice> selectByExampleGroupBySkip(SkipMaterialPriceExample example);
	 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    @DeleteProvider(type=SkipMaterialPriceSqlProvider.class, method="deleteByExample")
    int deleteByExample(SkipMaterialPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    
    @Delete({
        "delete from ${database}.skip_material_price",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("database")String database,@Param("id")Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    @Options(useGeneratedKeys=true)
    @Insert({
        "insert into skip_material_price (id, unit_price, ",
        "project, foreman, ",
        "mechainc, material_type, ",
        "base_price_type, create_date, ",
        "remark)",
        "values (#{id,jdbcType=INTEGER}, #{unitPrice,jdbcType=INTEGER}, ",
        "#{project,jdbcType=INTEGER}, #{foreman,jdbcType=INTEGER}, ",
        "#{mechainc,jdbcType=INTEGER}, #{materialType,jdbcType=INTEGER}, ",
        "#{basePriceType,jdbcType=INTEGER}, #{createDate,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR})"
    })
    int insert(SkipMaterialPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    @Options(useGeneratedKeys=true)
    @InsertProvider(type=SkipMaterialPriceSqlProvider.class, method="insertSelective")
    int insertSelective(SkipMaterialPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    @SelectProvider(type=SkipMaterialPriceSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="unit_price", property="unitPrice", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="project", property="project", jdbcType=JdbcType.INTEGER),
        @Result(column="foreman", property="foreman", jdbcType=JdbcType.INTEGER),
        @Result(column="mechainc", property="mechainc", jdbcType=JdbcType.INTEGER),
        @Result(column="material_type", property="materialType", jdbcType=JdbcType.INTEGER),
        @Result(column="base_price_type", property="basePriceType", jdbcType=JdbcType.INTEGER),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<SkipMaterialPrice> selectByExample(SkipMaterialPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    @Select({
        "select",
        "id, unit_price, project, foreman, mechainc, material_type, base_price_type, ",
        "create_date, remark",
        "from skip_material_price",
        "where id = #{id,jdbcType=INTEGER}",
          "and unit_price = #{unitPrice,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="unit_price", property="unitPrice", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="project", property="project", jdbcType=JdbcType.INTEGER),
        @Result(column="foreman", property="foreman", jdbcType=JdbcType.INTEGER),
        @Result(column="mechainc", property="mechainc", jdbcType=JdbcType.INTEGER),
        @Result(column="material_type", property="materialType", jdbcType=JdbcType.INTEGER),
        @Result(column="base_price_type", property="basePriceType", jdbcType=JdbcType.INTEGER),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    SkipMaterialPrice selectByPrimaryKey(SkipMaterialPriceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    @UpdateProvider(type=SkipMaterialPriceSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SkipMaterialPrice record, @Param("example") SkipMaterialPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    @UpdateProvider(type=SkipMaterialPriceSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SkipMaterialPrice record, @Param("example") SkipMaterialPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    @UpdateProvider(type=SkipMaterialPriceSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SkipMaterialPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    @Update({
        "update skip_material_price",
        "set project = #{project,jdbcType=INTEGER},",
          "foreman = #{foreman,jdbcType=INTEGER},",
          "mechainc = #{mechainc,jdbcType=INTEGER},",
          "material_type = #{materialType,jdbcType=INTEGER},",
          "base_price_type = #{basePriceType,jdbcType=INTEGER},",
          "create_date = #{createDate,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}",
          "and unit_price = #{unitPrice,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SkipMaterialPrice record);
}