package com.core.mapper;

import com.core.entity.SkipMaterialPrice;
import com.core.entity.SkipMaterialPriceExample.Criteria;
import com.core.entity.SkipMaterialPriceExample.Criterion;
import com.core.util.Utils;
import com.core.entity.SkipMaterialPriceExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class SkipMaterialPriceSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    public String countByExample(SkipMaterialPrice sp,SkipMaterialPriceExample example) {
   //     SQL sql = new SQL();
//        sql.SELECT("count(*)").FROM(Utils.getDatabase()+".skip_material_price");
//        applyWhere(sql, example, false);
//        sql.GROUP_BY("skip");
//        System.out.println(sql.toString());
//        sql.SELECT("").FROM(table);
        //sql.VALUES("project", "#{project,jdbcType=INTEGER}");
        String sql ="SELECT COUNT(*) AS total FROM ( SELECT mechainc FROM "+Utils.getDatabase()+".skip_material_price  WHERE project = "+sp.getProject()+" GROUP BY mechainc,project ) u ";
        return sql;
    }
    public String selectByExampleGroupBySkip(SkipMaterialPriceExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("unit_price");
        sql.SELECT("project");
        sql.SELECT("foreman");
        sql.SELECT("mechainc");
        sql.SELECT("material_type");
        sql.SELECT("base_price_type");
        sql.SELECT("create_date");
        sql.SELECT("remark");
        sql.FROM(Utils.getDatabase()+".skip_material_price");
        applyWhere(sql, example, false);
        sql.GROUP_BY("mechainc");
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        return sql.toString();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    public String deleteByExample(SkipMaterialPriceExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM(Utils.getDatabase()+".skip_material_price");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    public String insertSelective(SkipMaterialPrice record) {
        SQL sql = new SQL();
        sql.INSERT_INTO(Utils.getDatabase()+".skip_material_price");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUnitPrice() != null) {
            sql.VALUES("unit_price", "#{unitPrice,jdbcType=INTEGER}");
        }
        
        if (record.getProject() != null) {
            sql.VALUES("project", "#{project,jdbcType=INTEGER}");
        }
        
        if (record.getForeman() != null) {
            sql.VALUES("foreman", "#{foreman,jdbcType=INTEGER}");
        }
        
        if (record.getMechainc() != null) {
            sql.VALUES("mechainc", "#{mechainc,jdbcType=INTEGER}");
        }
        
        if (record.getMaterialType() != null) {
            sql.VALUES("material_type", "#{materialType,jdbcType=INTEGER}");
        }
        
        if (record.getBasePriceType() != null) {
            sql.VALUES("base_price_type", "#{basePriceType,jdbcType=INTEGER}");
        }
        
        if (record.getCreateDate() != null) {
            sql.VALUES("create_date", "#{createDate,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    public String selectByExample(SkipMaterialPriceExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("unit_price");
        sql.SELECT("project");
        sql.SELECT("foreman");
        sql.SELECT("mechainc");
        sql.SELECT("material_type");
        sql.SELECT("base_price_type");
        sql.SELECT("create_date");
        sql.SELECT("remark");
        sql.FROM(Utils.getDatabase()+".skip_material_price");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        SkipMaterialPrice record = (SkipMaterialPrice) parameter.get("record");
        SkipMaterialPriceExample example = (SkipMaterialPriceExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE(Utils.getDatabase()+".skip_material_price");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getUnitPrice() != null) {
            sql.SET("unit_price = #{record.unitPrice,jdbcType=INTEGER}");
        }
        
        if (record.getProject() != null) {
            sql.SET("project = #{record.project,jdbcType=INTEGER}");
        }
        
        if (record.getForeman() != null) {
            sql.SET("foreman = #{record.foreman,jdbcType=INTEGER}");
        }
        
        if (record.getMechainc() != null) {
            sql.SET("mechainc = #{record.mechainc,jdbcType=INTEGER}");
        }
        
        if (record.getMaterialType() != null) {
            sql.SET("material_type = #{record.materialType,jdbcType=INTEGER}");
        }
        
        if (record.getBasePriceType() != null) {
            sql.SET("base_price_type = #{record.basePriceType,jdbcType=INTEGER}");
        }
        
        if (record.getCreateDate() != null) {
            sql.SET("create_date = #{record.createDate,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE(Utils.getDatabase()+".skip_material_price");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("unit_price = #{record.unitPrice,jdbcType=INTEGER}");
        sql.SET("project = #{record.project,jdbcType=INTEGER}");
        sql.SET("foreman = #{record.foreman,jdbcType=INTEGER}");
        sql.SET("mechainc = #{record.mechainc,jdbcType=INTEGER}");
        sql.SET("material_type = #{record.materialType,jdbcType=INTEGER}");
        sql.SET("base_price_type = #{record.basePriceType,jdbcType=INTEGER}");
        sql.SET("create_date = #{record.createDate,jdbcType=VARCHAR}");
        sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
        
        SkipMaterialPriceExample example = (SkipMaterialPriceExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    public String updateByPrimaryKeySelective(SkipMaterialPrice record) {
        SQL sql = new SQL();
        sql.UPDATE(Utils.getDatabase()+".skip_material_price");
        
        if (record.getProject() != null) {
            sql.SET("project = #{project,jdbcType=INTEGER}");
        }
        
        if (record.getForeman() != null) {
            sql.SET("foreman = #{foreman,jdbcType=INTEGER}");
        }
        
        if (record.getMechainc() != null) {
            sql.SET("mechainc = #{mechainc,jdbcType=INTEGER}");
        }
        
        if (record.getMaterialType() != null) {
            sql.SET("material_type = #{materialType,jdbcType=INTEGER}");
        }
        
        if (record.getBasePriceType() != null) {
            sql.SET("base_price_type = #{basePriceType,jdbcType=INTEGER}");
        }
        
        if (record.getCreateDate() != null) {
            sql.SET("create_date = #{createDate,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        sql.WHERE("unit_price = #{unitPrice,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skip_material_price
     *
     * @mbg.generated Wed Jan 31 19:21:20 CST 2018
     */
    protected void applyWhere(SQL sql, SkipMaterialPriceExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}