package com.core.mapper;

import com.core.entity.TokenInfo;
import com.core.entity.TokenInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TokenInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_info
     *
     * @mbg.generated Tue Jan 16 10:22:51 CST 2018
     */
    @SelectProvider(type=TokenInfoSqlProvider.class, method="countByExample")
    long countByExample(TokenInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_info
     *
     * @mbg.generated Tue Jan 16 10:22:51 CST 2018
     */
    @DeleteProvider(type=TokenInfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(TokenInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_info
     *
     * @mbg.generated Tue Jan 16 10:22:51 CST 2018
     */
    @Delete({
        "delete from token_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_info
     *
     * @mbg.generated Tue Jan 16 10:22:51 CST 2018
     */
    @Insert({
        "insert into token_info (id, staff, ",
        "token, code, date)",
        "values (#{id,jdbcType=INTEGER}, #{staff,jdbcType=INTEGER}, ",
        "#{token,jdbcType=VARCHAR}, #{code,jdbcType=VARCHAR}, #{date,jdbcType=VARCHAR})"
    })
    int insert(TokenInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_info
     *
     * @mbg.generated Tue Jan 16 10:22:51 CST 2018
     */
    @InsertProvider(type=TokenInfoSqlProvider.class, method="insertSelective")
    int insertSelective(TokenInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_info
     *
     * @mbg.generated Tue Jan 16 10:22:51 CST 2018
     */
    @SelectProvider(type=TokenInfoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="staff", property="staff", jdbcType=JdbcType.INTEGER),
        @Result(column="token", property="token", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="date", property="date", jdbcType=JdbcType.VARCHAR)
    })
    List<TokenInfo> selectByExample(TokenInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_info
     *
     * @mbg.generated Tue Jan 16 10:22:51 CST 2018
     */
    @Select({
        "select",
        "id, staff, token, code, date",
        "from token_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="staff", property="staff", jdbcType=JdbcType.INTEGER),
        @Result(column="token", property="token", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="date", property="date", jdbcType=JdbcType.VARCHAR)
    })
    TokenInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_info
     *
     * @mbg.generated Tue Jan 16 10:22:51 CST 2018
     */
    @UpdateProvider(type=TokenInfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TokenInfo record, @Param("example") TokenInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_info
     *
     * @mbg.generated Tue Jan 16 10:22:51 CST 2018
     */
    @UpdateProvider(type=TokenInfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TokenInfo record, @Param("example") TokenInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_info
     *
     * @mbg.generated Tue Jan 16 10:22:51 CST 2018
     */
    @UpdateProvider(type=TokenInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TokenInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_info
     *
     * @mbg.generated Tue Jan 16 10:22:51 CST 2018
     */
    @Update({
        "update token_info",
        "set staff = #{staff,jdbcType=INTEGER},",
          "token = #{token,jdbcType=VARCHAR},",
          "code = #{code,jdbcType=VARCHAR},",
          "date = #{date,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TokenInfo record);
}