package com.core.mapper;

import com.core.entity.UnitTypeProject;
import com.core.entity.UnitTypeProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UnitTypeProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_project
     *
     * @mbg.generated Wed Dec 13 18:02:09 CST 2017
     */
    @SelectProvider(type=UnitTypeProjectSqlProvider.class, method="countByExample")
    long countByExample(UnitTypeProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_project
     *
     * @mbg.generated Wed Dec 13 18:02:09 CST 2017
     */
    @DeleteProvider(type=UnitTypeProjectSqlProvider.class, method="deleteByExample")
    int deleteByExample(UnitTypeProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_project
     *
     * @mbg.generated Wed Dec 13 18:02:09 CST 2017
     */
    @Delete({
        "delete from unit_type_project",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_project
     *
     * @mbg.generated Wed Dec 13 18:02:09 CST 2017
     */
    @Insert({
        "insert into unit_type_project (id, project, ",
        "base_id, type)",
        "values (#{id,jdbcType=INTEGER}, #{project,jdbcType=INTEGER}, ",
        "#{baseId,jdbcType=INTEGER}, #{type,jdbcType=INTEGER})"
    })
    int insert(UnitTypeProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_project
     *
     * @mbg.generated Wed Dec 13 18:02:09 CST 2017
     */
    @InsertProvider(type=UnitTypeProjectSqlProvider.class, method="insertSelective")
    int insertSelective(UnitTypeProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_project
     *
     * @mbg.generated Wed Dec 13 18:02:09 CST 2017
     */
    @SelectProvider(type=UnitTypeProjectSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="project", property="project", jdbcType=JdbcType.INTEGER),
        @Result(column="base_id", property="baseId", jdbcType=JdbcType.INTEGER),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER)
    })
    List<UnitTypeProject> selectByExample(UnitTypeProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_project
     *
     * @mbg.generated Wed Dec 13 18:02:09 CST 2017
     */
    @Select({
        "select",
        "id, project, base_id, type",
        "from unit_type_project",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="project", property="project", jdbcType=JdbcType.INTEGER),
        @Result(column="base_id", property="baseId", jdbcType=JdbcType.INTEGER),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER)
    })
    UnitTypeProject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_project
     *
     * @mbg.generated Wed Dec 13 18:02:09 CST 2017
     */
    @UpdateProvider(type=UnitTypeProjectSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UnitTypeProject record, @Param("example") UnitTypeProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_project
     *
     * @mbg.generated Wed Dec 13 18:02:09 CST 2017
     */
    @UpdateProvider(type=UnitTypeProjectSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UnitTypeProject record, @Param("example") UnitTypeProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_project
     *
     * @mbg.generated Wed Dec 13 18:02:09 CST 2017
     */
    @UpdateProvider(type=UnitTypeProjectSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UnitTypeProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_project
     *
     * @mbg.generated Wed Dec 13 18:02:09 CST 2017
     */
    @Update({
        "update unit_type_project",
        "set project = #{project,jdbcType=INTEGER},",
          "base_id = #{baseId,jdbcType=INTEGER},",
          "type = #{type,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UnitTypeProject record);
}