package com.core.mapper;

import com.core.entity.UnitTypeCombination;
import com.core.entity.UnitTypeCombinationExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UnitTypeCombinationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_combination
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    @SelectProvider(type=UnitTypeCombinationSqlProvider.class, method="countByExample")
    long countByExample(UnitTypeCombinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_combination
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    @DeleteProvider(type=UnitTypeCombinationSqlProvider.class, method="deleteByExample")
    int deleteByExample(UnitTypeCombinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_combination
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    @Delete({
        "delete from unit_type_combination",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_combination
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    @Options(useGeneratedKeys=true)
    @Insert({
        "insert into unit_type_combination (id, base_type, ",
        "material_spec, base_price_type, ",
        "material_type, remark)",
        "values (#{id,jdbcType=INTEGER}, #{baseType,jdbcType=INTEGER}, ",
        "#{materialSpec,jdbcType=INTEGER}, #{basePriceType,jdbcType=INTEGER}, ",
        "#{materialType,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(UnitTypeCombination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_combination
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    @Options(useGeneratedKeys=true)
    @InsertProvider(type=UnitTypeCombinationSqlProvider.class, method="insertSelective")
    int insertSelective(UnitTypeCombination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_combination
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    @SelectProvider(type=UnitTypeCombinationSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="base_type", property="baseType", jdbcType=JdbcType.INTEGER),
        @Result(column="material_spec", property="materialSpec", jdbcType=JdbcType.INTEGER),
        @Result(column="base_price_type", property="basePriceType", jdbcType=JdbcType.INTEGER),
        @Result(column="material_type", property="materialType", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<UnitTypeCombination> selectByExample(UnitTypeCombinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_combination
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    @Select({
        "select",
        "id, base_type, material_spec, base_price_type, material_type, remark",
        "from ${database}.unit_type_combination",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="base_type", property="baseType", jdbcType=JdbcType.INTEGER),
        @Result(column="material_spec", property="materialSpec", jdbcType=JdbcType.INTEGER),
        @Result(column="base_price_type", property="basePriceType", jdbcType=JdbcType.INTEGER),
        @Result(column="material_type", property="materialType", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    UnitTypeCombination selectByPrimaryKey(@Param("database")String database,@Param("id")Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_combination
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    @UpdateProvider(type=UnitTypeCombinationSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UnitTypeCombination record, @Param("example") UnitTypeCombinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_combination
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    @UpdateProvider(type=UnitTypeCombinationSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UnitTypeCombination record, @Param("example") UnitTypeCombinationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_combination
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    @UpdateProvider(type=UnitTypeCombinationSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UnitTypeCombination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_type_combination
     *
     * @mbg.generated Mon Dec 25 20:02:59 CST 2017
     */
    @Update({
        "update unit_type_combination",
        "set base_type = #{baseType,jdbcType=INTEGER},",
          "material_spec = #{materialSpec,jdbcType=INTEGER},",
          "base_price_type = #{basePriceType,jdbcType=INTEGER},",
          "material_type = #{materialType,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UnitTypeCombination record);
}