package com.core.mapper.main;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

import com.core.entity.main.Enterprise;

public interface EnterpriseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    @Delete({
        "delete from luqiao.enterprise",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    @Insert({
        "insert into luqiao.enterprise (id, name, ",
        "serial_number, password, ",
        "legal_person_idcard, mobile, ",
        "create_date, tip_date, ",
        "code, web_name, database_name, ",
        "remark)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{serialNumber,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{legalPersonIdcard,jdbcType=VARCHAR}, #{mobile,jdbcType=VARCHAR}, ",
        "#{createDate,jdbcType=VARCHAR}, #{tipDate,jdbcType=INTEGER}, ",
        "#{code,jdbcType=VARCHAR}, #{webName,jdbcType=VARCHAR}, #{databaseName,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR})"
    })
    int insert(Enterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    @Select({
        "select",
        "id, name, serial_number, password, legal_person_idcard, mobile, create_date, ",
        "tip_date, code, web_name, database_name, remark",
        "from luqiao.enterprise",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="serial_number", property="serialNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="legal_person_idcard", property="legalPersonIdcard", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="tip_date", property="tipDate", jdbcType=JdbcType.INTEGER),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="web_name", property="webName", jdbcType=JdbcType.VARCHAR),
        @Result(column="database_name", property="databaseName", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    Enterprise selectByPrimaryKey(Integer id);
    
    
    
    @Select({
        "select",
        "id, name, serial_number, password, legal_person_idcard, mobile, create_date, ",
        "tip_date, code, web_name, database_name, remark",
        "from luqiao.enterprise",
        "where mobile = #{mobile,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="serial_number", property="serialNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="legal_person_idcard", property="legalPersonIdcard", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="tip_date", property="tipDate", jdbcType=JdbcType.INTEGER),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="web_name", property="webName", jdbcType=JdbcType.VARCHAR),
        @Result(column="database_name", property="databaseName", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    Enterprise selectByMobile(String mobile);
    @Select({
        "select",
        "id, name, serial_number, password, legal_person_idcard, mobile, create_date, ",
        "tip_date, code, web_name, database_name, remark",
        "from luqiao.enterprise",
        "where mobile = #{mobile,jdbcType=VARCHAR} and code = #{code,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="serial_number", property="serialNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="legal_person_idcard", property="legalPersonIdcard", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="tip_date", property="tipDate", jdbcType=JdbcType.INTEGER),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="web_name", property="webName", jdbcType=JdbcType.VARCHAR),
        @Result(column="database_name", property="databaseName", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    
    Enterprise selectByMobileAndCode(@Param("mobile")String mobile,@Param("code") String code);
    
    @Select({
        "select",
        "id, name, serial_number, password, legal_person_idcard, mobile, create_date, ",
        "tip_date, code, web_name, database_name, remark",
        "from luqiao.enterprise",
        "where code = #{code,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="serial_number", property="serialNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="legal_person_idcard", property="legalPersonIdcard", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="tip_date", property="tipDate", jdbcType=JdbcType.INTEGER),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="web_name", property="webName", jdbcType=JdbcType.VARCHAR),
        @Result(column="database_name", property="databaseName", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    Enterprise selectByCode(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    @Select({
        "select",
        "id, name, serial_number, password, legal_person_idcard, mobile, create_date, ",
        "tip_date, code, web_name, database_name, remark",
        "from luqiao.enterprise"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="serial_number", property="serialNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="legal_person_idcard", property="legalPersonIdcard", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="tip_date", property="tipDate", jdbcType=JdbcType.INTEGER),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="web_name", property="webName", jdbcType=JdbcType.VARCHAR),
        @Result(column="database_name", property="databaseName", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<Enterprise> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    @Update({
        "update luqiao.enterprise",
        "set name = #{name,jdbcType=VARCHAR},",
          "serial_number = #{serialNumber,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "legal_person_idcard = #{legalPersonIdcard,jdbcType=VARCHAR},",
          "mobile = #{mobile,jdbcType=VARCHAR},",
          "create_date = #{createDate,jdbcType=VARCHAR},",
          "tip_date = #{tipDate,jdbcType=INTEGER},",
          "code = #{code,jdbcType=VARCHAR},",
          "web_name = #{webName,jdbcType=VARCHAR},",
          "database_name = #{databaseName,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Enterprise record);
}