package com.core.mapper.main;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

import com.core.entity.main.EnterpriseMeal;

public interface EnterpriseMealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_meal
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    @Delete({
        "delete from luqiao.enterprise_meal",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_meal
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    @Insert({
        "insert into luqiao.enterprise_meal (id, enterprise, ",
        "meal, expiry_date, ",
        "state)",
        "values (#{id,jdbcType=INTEGER}, #{enterprise,jdbcType=INTEGER}, ",
        "#{meal,jdbcType=INTEGER}, #{expiryDate,jdbcType=INTEGER}, ",
        "#{state,jdbcType=INTEGER})"
    })
    int insert(EnterpriseMeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_meal
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    @Select({
        "select",
        "id, enterprise, meal, expiry_date, state",
        "from luqiao.enterprise_meal",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="enterprise", property="enterprise", jdbcType=JdbcType.INTEGER),
        @Result(column="meal", property="meal", jdbcType=JdbcType.INTEGER),
        @Result(column="expiry_date", property="expiryDate", jdbcType=JdbcType.INTEGER),
        @Result(column="state", property="state", jdbcType=JdbcType.INTEGER)
    })
    EnterpriseMeal selectByPrimaryKey(Integer id);

    
    
    
    @Select({
        "select",
        "id, enterprise, meal, expiry_date, state",
        "from luqiao.enterprise_meal",
        "where enterprise = #{id,jdbcType=INTEGER} and state = #{state,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="enterprise", property="enterprise", jdbcType=JdbcType.INTEGER),
        @Result(column="meal", property="meal", jdbcType=JdbcType.INTEGER),
        @Result(column="expiry_date", property="expiryDate", jdbcType=JdbcType.INTEGER),
        @Result(column="state", property="state", jdbcType=JdbcType.INTEGER)
    })
    List<EnterpriseMeal> selectByEnterprise(@Param("id") Integer id,@Param("state") Integer state);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_meal
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    @Select({
        "select",
        "id, enterprise, meal, expiry_date, state",
        "from luqiao.enterprise_meal"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="enterprise", property="enterprise", jdbcType=JdbcType.INTEGER),
        @Result(column="meal", property="meal", jdbcType=JdbcType.INTEGER),
        @Result(column="expiry_date", property="expiryDate", jdbcType=JdbcType.INTEGER),
        @Result(column="state", property="state", jdbcType=JdbcType.INTEGER)
    })
    List<EnterpriseMeal> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_meal
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    @Update({
        "update luqiao.enterprise_meal",
        "set enterprise = #{enterprise,jdbcType=INTEGER},",
          "meal = #{meal,jdbcType=INTEGER},",
          "expiry_date = #{expiryDate,jdbcType=INTEGER},",
          "state = #{state,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(EnterpriseMeal record);
}