package com.core.mapper.main;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

import com.core.entity.main.ModuleMeal;

public interface ModuleMealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_meal
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    @Delete({
        "delete from luqiao.module_meal",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_meal
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    @Insert({
        "insert into luqiao.module_meal (id, module, ",
        "project_max_num, staff_max_num, ",
        "price, remark)",
        "values (#{id,jdbcType=INTEGER}, #{module,jdbcType=INTEGER}, ",
        "#{projectMaxNum,jdbcType=INTEGER}, #{staffMaxNum,jdbcType=INTEGER}, ",
        "#{price,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(ModuleMeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_meal
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    @Select({
        "select",
        "id, module, project_max_num, staff_max_num, price, remark",
        "from luqiao.module_meal",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="module", property="module", jdbcType=JdbcType.INTEGER),
        @Result(column="project_max_num", property="projectMaxNum", jdbcType=JdbcType.INTEGER),
        @Result(column="staff_max_num", property="staffMaxNum", jdbcType=JdbcType.INTEGER),
        @Result(column="price", property="price", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    ModuleMeal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_meal
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    @Select({
        "select",
        "id, module, project_max_num, staff_max_num, price, remark",
        "from luqiao.module_meal"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="module", property="module", jdbcType=JdbcType.INTEGER),
        @Result(column="project_max_num", property="projectMaxNum", jdbcType=JdbcType.INTEGER),
        @Result(column="staff_max_num", property="staffMaxNum", jdbcType=JdbcType.INTEGER),
        @Result(column="price", property="price", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<ModuleMeal> selectAll();

    
    
    @Select({
        "select",
        "id, module, project_max_num, staff_max_num, price, remark",
        "from luqiao.module_meal where id in (${ids})"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="module", property="module", jdbcType=JdbcType.INTEGER),
        @Result(column="project_max_num", property="projectMaxNum", jdbcType=JdbcType.INTEGER),
        @Result(column="staff_max_num", property="staffMaxNum", jdbcType=JdbcType.INTEGER),
        @Result(column="price", property="price", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<ModuleMeal> selectByIds(@Param("ids")  String ids);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_meal
     *
     * @mbg.generated Mon Dec 11 18:18:50 CST 2017
     */
    @Update({
        "update luqiao.module_meal",
        "set module = #{module,jdbcType=INTEGER},",
          "project_max_num = #{projectMaxNum,jdbcType=INTEGER},",
          "staff_max_num = #{staffMaxNum,jdbcType=INTEGER},",
          "price = #{price,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ModuleMeal record);
}